Procfile
client/package-lock.json
package-lock.json

This is a first attempt to fix a deployment problem.  When our package.json file's "start" script was modified to use nodemon instead of just node, Heroku started trying to use nodemon in the production environment as well, but the nodemon package is "pruned" from the deployed packages for production, so nodemon was not found when Heroku tried to start node.  By addind a Procfile to the Heroku web dyno that has a different start script, we can make sure that Heroku starts the node app with node instead of nodemon.  I believe Heroku has it's own mechanism for re-starting node apps when they fail. This allows us to use nodemon in the development environment for the convinience of auto-restarting the node app when files change, but also allow the Heroku deployment to work.  We'll see if this …

Added Procfile for Heroku

---

client/src/App.js
client/src/components/About.js
client/src/components/ContactUs.js
client/src/contexts/Toast/Toast.js
client/src/contexts/Toast/ToastContext.js
client/src/contexts/Toast/index.js
client/src/contexts/Toast/useToast.js
client/src/contexts/Toast/withToastProvider.js

Issue #123 
Added a Toast Context (instead of using a library)
- App.js is wrapped in a ToastProvider, which has properties `add` and `delete` for Toast.
- To use, call `const toast = useToast()`,  `import {} from "/src/contexts/Toast"`
To check out how it works, navigate to `/about` and `/contactus` rapidly.
Example of how to use:
- `toast.add("This is a new toast!")`
Note: Styling the toast can be modified.

Added toast functionality

---

client/src/components/ProjectWizard/WizardRuleInputList.js
client/src/components/ProjectWizard/WizardRuleInputPanels.js
client/src/components/TdmCalculationContainer.js
client/src/services/tdm-engine.js

Issue #217 
Temporary fix to remove the rendering of 2 inactive inputs. Inputs are still included in the calculation so as not to break the engine, but are not rendered on the page so user can not interact with it. Removal of the rendering is currently hard coded until permanent solution can be resolved.

conditionally hide unused inputs

---

client/src/components/ProjectWizard/WizardRuleInput.js

This fixes the problem of the forward button being disabled when viewing
existing projects with the required values filled in.
Fix for #218

Check current value not empty for required rules

---

client/src/App.js
client/src/components/LandingPage/LandingPageSectionEnd.js
client/src/components/LandingPage/LandingPageSectionHeroImage.js
client/src/components/NavBar.js
client/src/components/ProjectWizard/TdmCalculationWizard.js
client/src/components/ProjectWizard/WizardPages/ProjectDescriptions.js
client/src/components/Projects.js
client/src/components/TdmCalculationContainer.js
client/src/services/tdm-engine.js

- Issue #242 . Validations are now in place for wizard page 2 and are uniform with validations of page 1.
- Wizard routing moved to react-router, allowing for easier page checking through route params rather than state.
- Refreshing/reloading while inside the wizard now reverts the user to either page 1 or page 6 depending on access control.
- "New Project" link in nav bar is now checking route rather than context.
- Issue #266 . babel-eslint was not added to the project, but linter issue that was blocking commits was fixed by converting the TdmCalculationContainer into a functional component, as per @entrotech and @fyliu suggestion. Addition of babel-eslint module will be further discussed.

Validations and wizard routing

---

client/src/components/ProjectWizard/WizardPages/ProjectSummary.js

If a measure is of type "choice", the value "0" means the measure is not applied and should be hidden from the summary.

Attempt to fix problem with Summary Page of Wizard

---

client/src/components/Projects.js

Created search bar to enable global search of all columns (name, address, version number, building permit, entered by, created on, and last modified) in the projects table. 
Issue: #179

feat: create global search for project table

---

.grenrc.json
CHANGELOG.md
Contributing.md
client/package-lock.json
client/src/components/ProjectWizard/RuleStrategy/RuleStrategy.js
client/src/components/ProjectWizard/RuleStrategy/RuleStrategyList.js
client/src/components/ProjectWizard/RuleStrategy/RuleStrategyPanels.js
client/src/components/ProjectWizard/TdmCalculationWizard.js
client/src/components/ProjectWizard/WizardPages/ProjectMeasures.js
client/src/components/TdmCalculationContainer.js
client/src/services/tdm-engine.js
package-lock.json

I actually added this capability to all rules. You enable it in the database by setting the displayComment value to true in the corresponding row of the CalculationRule table. It displays as a resizeable textarea, and gets saved and restored with the other project inputs.
The textarea starts out with a default size two rows high If the content is longer than fits, a vertical scrollbar will appear, as well as a resize handle, which the user can drag to make the area larger.
I did not underline the last part of the label, as there is no clear action that should occur if the user clicks on it.
Closes Issue #318 
Closes #318

Add note to applicant defined strategy

---

client/package-lock.json
client/package.json
client/src/components/ProjectWizard/RuleStrategy/RuleStrategy.js

Partial Implementation of Issue #318. The strategy descriptions are available and currently displayed in a tooltip, but the tooltip style can use improvement. Also descriptions are missing from Rose's spreadsheet for Electiric Vehicle Bonus and Applicant-Defined STrategy.

First cut - need better styling of tooltip

---

client/src/components/Projects.js
client/src/components/TdmCalculationContainer.js
client/src/services/project.service.js
middleware/jwt-session.js
server.js

Closes #351 and #348.
A logged-in user's session expires after 14 days (instead of 1 day), and when it does expire, they see a toast telling them that their session expired, and re-directing them to the login page. This happens for the Project page initial fetch, and potentially when trying to save a project (in which case the user will lose any work they have done on the project).
Also force redirect of http server requests to https.

Fix token expiration handling for Issue #351

---

client/src/components/ProjectWizard/TdmCalculationWizard.js
client/src/components/ProjectWizard/WizardPages/ProjectMeasures.js

Fixes issue with the spacing of the Residential and Employment Pkg Select buttons on the Project Measures page when both are selected.
finishes the first element of issue #386

Project measures top row spacing

---

client/src/App.js
client/src/components/ProjectWizard/RuleStrategy/RuleStrategy.js
client/src/components/ProjectWizard/TdmCalculationWizard.js
client/src/components/ProjectWizard/WizardPages/ProjectMeasures.js
client/src/components/TdmCalculationContainer.js
client/src/components/useLocalStorage.js

- Moved state for whether the display box is open or not to local storage for persistence across sessions
- found useful useLocalStorage hook to manage this simply.
- Styled tooltips on ProjectMeasures page to align on the right and to match the style of the figma
closes #294 
**BEFORE**
**AFTER**

Issue 294 fixes - Tooltip style, and infobox state in localStorage

---

client/src/components/TdmCalculationContainer.js

To prevent the problem of a user still being able to see their own project data after logging out.
Just made the call to an existing project contigent upon their being a logged in user within the initiateEngine useEffect. And made the useEffect rerun on changes to account. Now when a user logs out the initateEngine will clear its own form inputs.
As mentioned in issue 400, this does not touch the jwt cookie on logout, which could potentially be a security issue.
One potential issue I can see with this solution is that a user will lose all their data if they're working on an unsaved project and log out. However, since a user who isn't logged in can't save a project anyway I'm not sure that this matters.
closes #400

Clear Project Data on Logout

---

client/src/components/ProjectWizard/TdmCalculationWizard.js
client/src/components/Sidebar.js

The sidebarContainer element is now sticky. As far as I can tell it all works and there are no adverse effects on the sidebar on other pages or sizes.
closes #405

Wizard Sidebar Content is sticky

---

client/src/components/ProjectWizard/WizardPages/ProjectSummary.js

#421 Missed the top of project summary in last commit. I added a conditional rendering of the date last saved so that it does not show when you are creating a project for the first time.

Add conditional rendering of date last saved to top of Project Summary

---

db/flyway-config.js

In a JDBC connection string the correct way to escape a database name which might have special characters in it (in this case the production environment has a database name with spaces in it), is to enclosed the database name in braces.
It seemed to work fine escaping the database name with double-quotes on Windows, but caused problems on a Mac.

Change escaping of database name in JDBC connection string for Flyway

---

db/migration/V0012__put_warehouse_calculation_panel_back_478.sql

Migration V0008 deleted the CalculationPanel record for Warehouse, but we need it, so this migration inserts it again.

Insert warehouse CalculationPanel again

---

client/src/components/ProjectWizard/SidebarPoints/SidebarPoints.js
client/src/components/ProjectWizard/SidebarPoints/SidebarPointsPanel.js
client/src/components/ProjectWizard/SidebarPoints/SidebarProjectLevel.js
client/src/components/ProjectWizard/SidebarPoints/ToolTip.js

I added tooltip messages within the Project Wizard for the Sidebar section - "Project Level”, "Target Points", and "Earned Points".
#433

Added Tooltips to Sidebar

---

client/src/components/ProjectWizard/SidebarPoints/SidebarPoints.js
client/src/components/ProjectWizard/SidebarPoints/SidebarProjectLevel.js
client/src/components/ProjectWizard/SidebarPoints/ToolTip.js

#524 
I revised the ToolTips within the Sidebar so that only the first word of each sentence would be capitalized along with any pertinent terms that warrant capitalization.
I also added functionality in order to have the Tooltips display conditionally. If "Project Level" or "Target Points" equal zero than the Tooltip icon will not be displayed. Once the value is greater than zero the Tooltip icon will be displayed along with conditionally displayed Tooltip message.

Corrected capitalization of tooltips and made display of tooltips conditional

---

client/package-lock.json
client/src/components/ProjectWizard/RuleStrategy/RuleStrategyPanels.js
client/src/components/ProjectWizard/TdmCalculationWizard.js
client/src/components/ProjectWizard/WizardPages/ProjectMeasures.js
client/src/components/TdmCalculationContainer.js
db/migration/V972020.10465__packages_only_apply_to_level_one_550.sql
package-lock.json

If project is level 1,
Hide the package selection buttons from the Strategies page
Hide the Package Bonus Section of the Measure page
Remove package bonus points from the earned point calculation (they should not be selectable anyway, but this is a safeguard to prevent edge cases where user might be able to somehow select a pkg and earn a pkg bonus point).
Closes Issue #550 #551

Package bonus should only apply to level 1 projects

---

client/src/styles/Calculation.scss

I corrected the alignment of the right button on the second page of the wizard, the project specifications page. #548

Fix alignment of right button on specifications page, when disabled #548

---

client/src/components/Button/Button.js
client/src/components/Button/NavButton.js
client/src/components/Button/SwitchViewButton.js
client/src/components/ProjectSinglePage/TdmCalculation.js
client/src/components/ProjectWizard/TdmCalculationWizard.js
client/src/styles/theme.js

Part of #563: make buttons consistent
- Refactored Button component to make it more reusable (If we need to add custom styles for a component, we can pass it into className)
- Restyled buttons to incorporate recently-learned Material's design best practices (e.g. Less amount of emphasis on "Start Over," more emphasis/drop shadows on nav button, a less emphasis on "save project")
- Add Project and Start Over buttons are inline
- Incorporated contained and outlined variant of buttons
- Add SwitchViewButton back in, but is now using the Button component
- Add a few more colors in theme
Page 1 (disabled -- uses all the same style as the enabled nav button but just greyed out and no pointer; didn't know which grey to use so I arbitrarily chose one):
Page 2-4:
Page 5:

More buttons styling and refactoring

---

client/src/components/Projects.js
client/src/components/TermsAndConditionsModal.js

Edited the toast to only display once in order to notify users after login information has timed out. #506
Also included styling changes to scrollbar for the Terms and Conditions Modal per request.

Bug: The toast to notify users after login information has timed out is displayed twice #506 

---

client/src/App.js
client/src/components/NavConfirmationModal.js
client/src/components/ProjectWizard/TdmCalculationWizard.js
client/src/components/TdmCalculationContainer.js

This PR addresses part of issue #595. I'm still working on issue but wanted to get some work sent in for Tuesday's meeting.
- A NavConfirmationModal shows up when attempting to navigate away from /calculation (e.g. /about, /login, etc.) when form is filled out and new updates have not been saved; Added react-router Prompt component
- Modal does not yet show up when user clicks on Start Over - Still working on this
Did some minor refactoring/code clean up:
- deconstructed all props in TdmCalculationContainer.js
- deleted unused functions (setTokenInHeaders in App.js)
- made usage of Toast and History consistent; deleted repetitive ToastContext and opted for useToast instead

NavConfirmationModal shows up when attempting to navigate away from /calculation

---

client/src/App.js
client/src/components/Projects/DeleteProjectModal.js
client/src/components/Projects/DuplicateProjectModal.js
client/src/components/Projects/ProjectActionModal.js
client/src/components/Projects/ProjectsPage.js

refactoring opportunity as part of issue #609 
- Refactored Delete and Duplicate Modals into their own component (Reduced ProjectsPage component by 200 lines of code!)
- Created reusable `ProjectActionModal` that contains shared styling and behavior for the Delete and Duplicate Modals
- Renamed `Project`s component to `ProjectsPage`
- Moved all Projects page related components into its own folder (under `/Projects`)

Refactor projects page and move duplicate and delete modals into own component

---

client/src/App.js
client/src/components/Header.js
client/src/components/NavBar.js
client/src/components/NavBarLogin.js

Closes #660 
- Made sure to set local storage to `{}` if there is no currentUser in localStorage
- Refactored and removed unnecessary setAccount in NavBarLogin component

Fix nav and login bug related to setting account and local storage #660

---

client/src/components/ProjectWizard/TdmCalculationWizard.js
client/src/components/Projects/ProjectActionModal.js
client/src/components/Projects/ProjectsPage.js
client/src/components/TdmCalculationContainer.js

closes #662 
console warnings:
- Fixed some console warnings by adding a condition to check if there's a selectedProject
- Deleted unused "toggleCancelButton" prop because it's the same as the "toggleCloseButton" prop
NavConfirmationModal
- for some reason, when the `toast.add("Saved New Project")` is invoked _before_ the `history.push(newPath),` it causes the NavConfirmationModal to appear even tho the user has already saved the project. Not exactly sure why it's only happening on the project strategies page, but when I changed the order of the invocations, that seemed to have resolved the problem. 
```
// changed order to:
history.push(newPath);
setFormHasSaved(true);
toast.add("Saved New Project");
```
Also, did some minor refactoring

Fix confirmation modal bug #662

---

client/src/contexts/Toast/Toast.js
client/src/contexts/Toast/withToastProvider.js

Changed CSS so that toasts stays in top center of screen regardless of screen size and follows window, so user will notice even on the longer pages. Also changed the timer to 8 seconds.

#407 Toasts now fixed to top of screen

---

client/src/contexts/Toast/Toast.js

Toast is now centered on the right side of the page, ignoring the sidebar, and has Z index set to one so it pops up over the sidebar in mobile view.

Toast now centered on right side container

---

client/src/components/PublicComment/PublicCommentPage.js
server/.env-example
server/app/services/public-comment.service.js
server/app/services/sendgrid-service.js

closes #658 
When running `git commit` command, got this error: 
When I tried installing husky as instructed, it kept trying to run `npm run lint` on this file `node_modules/asn1.js.` But because this supposed to be ignored, it kept erroring out.  
I managed to get it to commit and push but if you can double check on the linting, that would be helpful. Thank you!

Add email capabilities to public comment page #658

---

client/src/components/ProjectWizard/RuleCalculation/RuleCalculation.js
client/src/components/ProjectWizard/RuleInput/RuleInput.js
client/src/components/ProjectWizard/RuleStrategy/RuleStrategy.js
client/src/components/ProjectWizard/SidebarPoints/SidebarPoints.js
client/src/components/ProjectWizard/SidebarPoints/SidebarProjectLevel.js

Changed both tooltips to the react-tooltips library and standardized the CSS. However, have not removed the old Sidebar/tooltip file. 
#671

#671 Refactored Sidebar and Calculator Tooltips

---

client/package-lock.json
client/src/components/ProjectWizard/SidebarPoints/SidebarPoints.js
server/package-lock.json

Increased Size of Earned Points and Target Points on Sidebar to be equal to Project Level #712

Changed font-size for earned and target points

---

client/src/components/ProjectWizard/RuleCalculation/RuleCalculation.js
client/src/components/ProjectWizard/RuleInput/RuleInput.js
client/src/components/ProjectWizard/RuleInput/RuleInputLabel.js
client/src/components/ProjectWizard/RuleStrategy/RuleStrategy.js
client/src/components/ProjectWizard/RuleStrategy/RuleStrategyLabel.js
client/src/components/ProjectWizard/WizardPages/ProjectPackages.js
client/src/components/ToolTip/ToolTipIcon.js
client/src/components/ToolTip/ToolTipLabel.js
client/src/styles/theme.js

closes #671 
- Refactor and create ToolTipLabel and RuleInputLabel
- Delete unused code and styling from RuleInput
Third commit:
-  Remove unused code
- Fix tooltip for parking baseline to only show up on tooltip icon (not label)
- Rename variables and classname
- Use jss theme colors when hovering on rows
- Make RuleStrategy and RuleInput styles more consistent with each other
- Restyled RuleStrategy so that columns and dropdowns are consistent and aligned
- Refactor disabled styling & logic in RuleStrategy
- Create new RuleStrategyLabel component
Apologies ahead of time for overloading the last commit. It  includes some styling changes I made to the strategies page to clean it up a git.

671 refactor tooltips pt3

---

client/src/App.js
client/src/components/About.js
client/src/components/Authorization/Login.js
client/src/components/Authorization/Register.js
client/src/components/Authorization/ResetPassword.js
client/src/components/Authorization/ResetPasswordRequest.js
client/src/components/Pagination.js
client/src/components/PrivacyPolicy.js
client/src/components/Projects/ProjectsPage.js
client/src/components/PublicComment/PublicCommentPage.js
client/src/components/Sidebar.js
client/src/components/TermsAndConditions.js
client/src/components/TermsAndConditions/TermsAndConditionsPage.js

closes #716 
Refactor usage of sidebar -
- Reorganize routes so that most routes are displaying the same Sidebar component; the Sidebar component does not need to be imported directly into the component
- /projects and /calculation pages do not use the same shared Sidebar component; /projects page has no sidebar and /calculation (TdmCalculationWizard.js) still has Sidebar imported in because it needs the SidebarPanel with the points displayed and calculated. It's the only page/component that a sidebar that behaves differently from the rest of the app.
- Clean up Sidebar component to make it more React-y
Note: the /confirm/ page now has a sidebar but the page itself needs to be styled. I added a new issue for that #738 
I also made two small style changes on the projects page, which are …

716 refactor sidebar and fix minor styling changes on projects page

---

client/src/components/Authorization/Login.js
server/app/services/account.service.js
server/app/services/sendgrid-service.js

Closes #756 
Side note - Reposting from [slack post](https://hackforla.slack.com/archives/CKY65G266/p1614568234007300). It has not yet been made into an issue: 
i just tried logging in with an unconfirmed email 3 times, saw 3 registration confirmation emails, tried clicking on the oldest email link and it verified me. Not sure if this is expected behavior or if only the most recent email link should be allowed to verify the user.

#756 Fix error message and resends email when user tries to login with unconfirmed email

---

client/src/components/ProjectWizard/WizardPages/ProjectSummary.js
client/src/components/ProjectWizard/helpers.js

closes #805
- add commas to numbers
- Made some styling changes - helps with some responsiveness and alignment of the columns
- deleted unused styling
Regular screen:
Large screen
Smaller screen

Add commas to numbers and clean up styling on calculation summary page #805

---

server/db/migration/V20210608.0016__fix_ids_and_switch_cases_for_dropdowns_839_848.sql

Closes #848
Bug was introduced due to #839. 
Bug Fix: update IDs of choices and switch cases in function body for the points. Use the same numbers across the different strategies for consistency. See migration file.

Fix dropdown bug #848 #839

---

client/src/components/ProjectWizard/WizardPages/ProjectSummary.js

#850 User strategy entered on 4th page now appears on 5th(Summary) page.

850 add user strategy to summary

---

server/app/services/tedious-pool.js

This is necessary because node-mssql v7 defaults to not trusting
self-signed certificate
Closes #932

Add config for trusting sql server certificate

---

server/app/services/tedious-pool.js

Fixes #932 
Original fix was written such that any nont-null value of SQL_TRUST_SERVER_CERTIFICATE was interpreted as true.
Modified so that only the value of "true" is interpreted as true, so, for example
```
SQL_TRUST_SERVER_CERTIFICATE=false
```
is now evaluated to false, as it should be set for all environments except a db running in a local docker container.
Also updated the .env file on the G-Drive to reflect the appropriate setting for each environment.

Minor tweak to Issue 932

---

client/src/components/Authorization/Login.js
client/src/components/ProjectWizard/WizardPages/ProjectSummary/ProjectSummary.js

#850 
1. Alignment moved to the left.
2. Spelling for User-Defined Strategy Details
3.Margin for summary text fixed.
4. Using class for the "Earned" box border at the top. borders should be identical now.
5. No coding changes, but can't seem to replicate this issue. Contacting Fang to see if he fixed it without notifying me. I'll keep an eye on it.

border, margins, and alignment fixed

---

client/src/components/ToolTip/ToolTipLabel.js

The package strategies at the top aren't showing tooltip icons anymore
Closes #940

Hide tooltip icon for package strategies

---

client/src/components/Checklist/ChecklistContent.js
client/src/components/ProjectWizard/WizardPages/Level0Page.jsx

Closes #1216 
- Updated link to the June 2002 url
Screenshot below showing updated link when hovering over link text.
- Updated link to the June 2022 url

1216 update link to revised tdm ordinance

---

client/package-lock.json
client/src/components/Button/Button.js
client/src/components/Button/EditToggleButton.js
client/src/components/Checklist/ChecklistContent.js
client/src/components/Faq/Answer.jsx
client/src/components/Faq/FaqView.jsx
client/src/components/Pagination.js
client/src/components/PdfPrint/PdfPrint.js
client/src/components/ProjectWizard/WizardPages/DiscoverTooltips.js
client/src/components/ProjectWizard/WizardPages/ProjectMeasures.js
client/src/components/ProjectWizard/WizardPages/ProjectSummary/ProjectInfo.jsx
client/src/components/ProjectWizard/WizardPages/ProjectSummary/ProjectInfoContainer.jsx
client/src/components/ProjectWizard/WizardPages/ProjectSummary/ProjectInfoList.jsx
client/src/components/ProjectWizard/WizardPages/ProjectSummary/ProjectSummary.js
client/src/components/ToolTip/ToolTipLabel.js
client/src/components/UI/AriaModal/ModalDialog.js
client/src/styles/App.scss
client/src/styles/AuthForms.css
client/src/styles/_variables.scss
client/src/styles/theme.js

Fixes #1282 Bug where modal backdrop did not cover the entire #body element, which caused the modal content to sometimes be above the viewable area if the screen was scrolled down.  Also adjusted backdrop opacity to be consistent with the Design for the "Laeve the Project Wizard Dialog".
Also modified the App.scss file to agree with the Design System Typography specs, so it is not normally necessary to explicitly apply styles to `<h1> - <h3>, <p> or <button>` elements to get typography consistent with the Design System.  This is a partial fix to Issue #1341.
In several places the text was made bold by applying the "Calibri Bold" font instead of the usual "Calibri" font. Then if the developer attempted to make the font more bold by applying a font-weight of 700, or the <strong> element, it …

1282 fix modal dialog backdrop

---

.husky/pre-commit
client/.prettierrc.js
client/src/App.js
client/src/components/ArchiveDelete/ProjectsArchive.js
client/src/components/ArchiveDelete/RolesArchive.js
client/src/components/ArchiveDelete/RolesContextMenu.js
client/src/components/ArchiveDelete/RolesDeleteContextMenu.js
client/src/components/ArchiveDelete/RolesUnarchiveContextMenu.js
client/src/components/Authorization/Login.js
client/src/components/Roles.js
client/src/services/account.service.js
client/src/services/project.service.js
server/.prettierrc.js
server/app/controllers/account.controller.js
server/app/controllers/project.controller.js
server/app/routes/account.routes.js
server/app/routes/project.routes.js
server/app/services/account.service.js
server/app/services/project.service.js
server/db/migration/V20230909.2141__archives_and_deletes_users_and_projects.sql
server/report.html
server/report.json

This PR solves #1395 
Implemented an end-to-end feature, creating a workflow that allows security admins to archive, un-archive/restore, and delete users along with their corresponding projects. 
- **Archiving Users:** Security admins can now archive users. 
- **Un-archiving/Restoring Users:** Security admins can also un-archive and restore users.
- **Deleting Users and Projects:** Security admins can permanently delete users and the user's respective projects.
- **UI Enhancements:** Added buttons and confirmation modals to ensure admins understand the implications of their actions.
- Created a migration script to alter the tables "Login" and "Project" to add an `archivedAt` column that is set to `NULL` by default or to a timestamp if queried
- Created new, protected API endpoints: 
- …

Adds end-to-end feature for archiving and deleting user accounts

---

client/src/components/Faq/Answer.jsx
client/src/components/Faq/CategoryInput.jsx
client/src/components/Faq/FaqCategory.js
client/src/components/Faq/Question.jsx

Fixes for issues called out in https://github.com/hackforla/tdm-calculator/issues/1311 9/6/23 meeting:
- Left-Align all Categories and FAQs
- Add 'Answer' placeholder
- Fix HTML divs and links
- Reset 'New FAQ' logic after user clicks 'Save Edits' - this will prevent a blank category or FAQ from persisting after user navigates back to edit mode
Items that need to be worked on:
- Warning dialog for Saving edits

Add placeholder, fix answers, reset new FAQ when done editing

---

client/src/components/Faq/Answer.jsx
client/src/components/Quill.js

- Fix for issue of answer editor exiting when setting a hyperlink from the text editor mentioned during 9/27/23 meeting on #1305 
- Additionally, this removes tools from the text editor that do not work for this iteration of the feature.

Add additional check for react-quill tooltip when editing an answer

---

client/src/components/PrivacyPolicy.js

Changed the email on the Privacy Policy Page 
✅On the Privacy Policy Page, change the email at the bottom from "[TDM-Calculator@hackforla.org](mailto:TDM-Calculator@hackforla.org)" to "[tdm@hackforla.org](mailto:tdm@hackforla.org)"

Solved issue #1454

---

client/src/components/ToolTip/ToolTipLabel.js

Closes #1402 
Hover state:
-Remove bold, underlined hover state
-Add a navy blue (#002E6D) 'i' or information icon next to regular text term
Clicked state:
-Change term text colour to 'navy blue' (#002E6D)
-Bold term text

Removed hover from items without descriptions

---

server/db/migration/V20231102.0946__modify_project_snpshot_sproc_1437.sql
server/report.html
server/report.json

Partial fix to #1437
update Project_Snapshot sproc to accept optional project name to rename the project while creating the snapshot
per Issue #1437 
none

Modified Project_Snapshot sproc

---

.github/workflows/tdm-server-tests.yml
push.sh
server/.env.example
server/_jest-setup_/global-setup/global-setup.js
server/_jest-setup_/utils/env-setup.js

- decoupled the test env from the dev env
- this will make it simpler to run tests concurrently with server and client running
1. Dev must open Docker (desktop)
2. cd into the `server` directory and run:  
```
npm test
```
Upon Approval, I can edit the [Test Wiki](https://github.com/hackforla/tdm-calculator/wiki/Testing)

Decouples Server Testing Environment from Dev Environment

---

server/__tests__/account.test.js

Follows code style and conventions discussed in #1521 
- Split up tests into different 'describe blocks' and added 'before' block into them.
-  The tests remain the same, but improved, so they are isolated.
- Addresses tech debt: makes the previously written tests more robust and clearer to understand/maintain

Refactors Account API Endpoints Tests

---

client/src/components/ArchiveDelete/ProjectsArchive.js
client/src/components/ArchiveDelete/RolesArchive.js
package-lock.json
package.json

Fixes #1453 
- On archivedaccounts page, changed link wording to "Return to Active Accounts"
- On archivedprojects page, changed link working to "Return to Active Accounts"
- Wording changed to better indicate what the link will route to.
Used the securityadmin@dispostable.com account for testing.
<details>
</details>
<details>
</details>

changed link wording in Archived Accounts and Projects

---

client/src/components/Roles.js

Fixes #1458 
- Added Registration Date and Email Confirmed columns to the Security Roles Page
- Populated data to the columns
- To know a user's registation date and if their email is confirmed
<details>
</details>
<details>
</details>

Updated security roles page with reg date and email confirmed columns/data - 1458

---

client/src/components/Faq/FaqView.jsx

Fixes #1511
- Replaced boolean expression with ternary
- To remove warning about receiving `false` for a non-boolean attribute `className`
No visual changes

Resolved bug for FAQ page for className attribute - 1511

---

.github/workflows/tdm-server-tests.yml
server/package-lock.json
server/package.json

Fixes #1522 
- updated mssql package from 8.1.0 to 10.0.1
- `$ npm install mssql@latest --save`
- Github Action in CI workflow 
- updated node from version 14 -> LTS after mssql dropped support for version 14
- For up-to-date package security and features
- I had no package conflicts or breaking changes. I tested with the server connected to the shared db and I ran the server tests with a docker instance for the db. I then manually checked our current syntax against the up to [date docs](https://tediousjs.github.io/node-mssql/) for the services we don't have automated coverage on, and everything looked good to me. 
- [latest docs](https://tediousjs.github.io/node-mssql)
- [releases](https://github.com/tediousjs/node-mssql/releases)

Updates mssql package in the server from 8.1.0 to 10.0.1

---

client/src/components/Projects/FilterDrawer.js
client/src/components/Projects/ProjectsPage.js

Fixes #1576 
- The Filter drawer has been moved to the right side of the screen. And the  << has been aligned properly.
- The animation will slide in/out from the right.
- The changes was made following the post stake holder meeting decision to put the filter drawer to the right.
<details>
</details>
<details>
</details>

Moved filter drawer to the right side of the screen

---

client/src/components/PrivacyPolicy.js

Fixes #1588
- Converted the first h3 element SCSS className to JSS CSS className.
- Cleaning up CSS code to maintain in one place so that there are less issues.
The securityadmin@dispostable.com account was used.
<details>
</details>
<details>
</details>

Converted first h3 element from SCSS to JSS CSS

---

client/src/components/ProjectWizard/WizardPages/ProjectSpecifications.js

Fixes #1599
- Converted one h3 element with the content "Project Level (left panel)" from SCSS to JSS format.
- To consolidate CSS to fewer places to minimize styling issues.
The [securityadmin@dispostable.com](mailto:securityadmin@dispostable.com) account was used.
<details>
</details>
<details>
</details>

Converted SCSS to JSS in ProjectSpecifications.js

---

client/src/components/ProjectWizard/WizardPages/ProjectSummary/ProjectSummary.js
client/src/components/ProjectWizard/WizardSidebar/SidebarPoints.js
client/src/components/ProjectWizard/WizardSidebar/SidebarPointsPanel.js

Fixes #1610, #1611, #1612
- Converted the SCSS CSS to JSS CSS for SidebarPoints, SidebarPointsPanel, and ProjectSummay pages
- Refactoring CSS code so that the CSS rules are in consolidated places.
The ladot@dispostable.com account was used.
<details>
</details>
<details>
</details>

converted SCSS to JSS CSS

---

client/src/components/Projects/pdfCsvData.js

Fixes #1574
- In the CSV download, columns representing multiple choice strategies where the N/A option is selected has been removed.
- [TDM EXAMPLE CSV](https://docs.google.com/spreadsheets/d/1fPj-RdfQjyTF7hSXwZpKB8KwhqQC2B4ZpjbjvznYbBw/edit#gid=414913169) please see spreadsheet linked to view example.
- The N/A choice does not need to be represented since it means that the strategy is not used, saving space and making the CSV file more efficient.
Account ladot@dispostable.com was used for testing.
There are no Screenshots, since there are no visible changes to the website.

removed N/A columns from CSV export

---

client/src/components/Projects/DeleteProjectModal.js
client/src/components/Projects/MultiProjectToolbarMenu.js
client/src/components/Projects/ProjectContextMenu.js

Fixes #1661 
- Changed the green color of restore trash icon back to default color.
- Changed the green color from the restore button back to red.
- The green color was not accessibility compliant.
The account tdm@hackforla.org was used for testing.
<details>
</details>
<details>
</details>

removed the green color from restore trash icon

---

client/src/components/ProjectWizard/WizardPages/ProjectSummary/ProjectInfo.jsx
client/src/components/Projects/csvData.js
server/db/migration/V20240501.1524__.changes_to_csv_format_1679.sql

Fixes #1679
- Added Bike Bonus Column after the other Bike-related Strategy Columns. The value is the number of points, rather than Y or N, since it is a computed value.
- Added the Car Share Bonus column after the other Car Share columns. The value is a number, indicating the number of points (0 or 2), since it is a computation.
- Modified column data for boolean strategies to be either "Y" or "N", instead of "TRUE" or blank.
- Modified numeric column values to represent 0 as "0" rather than a blank column
- Add column for the User-Defined Strategy as the last column.
- Requested by Emily Gable.
None

Changes to CSV format

---

client/src/components/ProjectWizard/WizardSidebar/SidebarCart.js
client/src/components/ProjectWizard/WizardSidebar/WizardSidebar.js

Fixes #1670 
- Adjusted the main div in the WizardSidebar component for height less than 800px
- Sidebar was overlapping the footer when the browser height is less than 800px
<details>
</details>
<details>
</details>

1670 - Ajusted WizardSidebar div that overlapped footer

---

client/src/components/PdfPrint/PdfFooter.js
client/src/components/PdfPrint/PdfPrint.js
client/src/components/Projects/MultiProjectToolbarMenu.js
client/src/components/Projects/ProjectTableRow.js

Fixes #1675 
- Added timestamps to PDF footer
- Timestamps are for: Snapshot, last saved, date printed
- To allow user to see relevant project dates and time when printing a project
- To format timestamps as `YYYY-MM-DD, 11:03 AM Pacific Time` or `YYYY-MM-DD, HH:MM:SS Pacific Time`
<details>
</details>
<details>
**With snapshot date**
**Without snapshot date**
</details>

1675 - Added project timestamps to PDF footer

---

client/src/components/ProjectWizard/TdmCalculationContainer.js
client/src/components/ProjectWizard/TdmCalculationWizard.js

Fixes #1710 
modified the "navigate away" line on save for new projects to point toward a different variable.
Changed the check for the popup modal to NOT trigger if the page the user is navigating away from is has a project id of 0.
When navigating to a new path on save, the navigation function now grabs the correct page number, so it should navigate users back to the same page they saved on, rather than a "N/A" page number.
The popup modal was triggered by url change from a project with no id number (such as from a new project) to a project with an id number. I set the modal to not trigger if the first url had no project id number. 
<details>
</details>

1710 saving new project bug

---

client/package-lock.json
client/src/components/Projects/ProjectsPage.js
client/src/components/UI/Pagination.js
package-lock.json
package.json

Fixes #1701
- Implement ability to choose how many page links are visible in the Pagination component via props
- Implement functionality to always display first and last page links
- Remove the navigate to last / first page buttons as they became redundant.
- Completing an issue (# 1701)
<details>
</details>
<details>
</details>

1701 sibling page for items in my project

---

client/package-lock.json
client/package.json
client/src/components/About.js
client/src/components/Checklist/ChecklistModal.js
client/src/components/UI/AriaModal/ModalDialog.js

Fixes #1682
- Determined that we can use any of several sets of free icons without impact to the bundle size.
- Migrated the icons on the CheckListModal and About page to use react-icons instead of importing @fortawesome.  These are the exact same icons, but just us a different import mechanism.
- We could follow-up by changing the import of all the @fortawesome icons in the app, or wait for design to decide what icons they want to use.
- Per request by UI Design to use an icon set with a larger number of available icons.
-
-
(none)
n/a

Start switch to react-icons

---

client/src/components/ProjectWizard/TdmCalculationContainer.js
server/db/migration/V20240619.1716__remove_strategy_info_5_1737.sql

Fixes #1737
- See Issue
- See Issue
(none)
<details>
</details>
<details>
</details>

Removed School Safety Campaign Strategy from rules

---

client/src/components/Projects/CopyProjectModal.js
client/src/components/Projects/ProjectsPage.js

Fixes #1716 
-Set the duplication project function to give a new project an empty string for a description if the original project did not have a description value.
-set the duplicate modal to utilize "useEffect" to update the selected projects name.
-The duplicate project function wasn't working because of a 400 Error in the Axios call: the description of the duplicate project has to be a string value. Previously, the duplicated project would use 'null'. This pull request adds a line to check if the description value is 'null', changes it into an empty string, then creates the duplicate.
-(oddly enough, have "undefined" for a description value works fine. This is the value currently used when creating brand new projects.)
- The duplicate modal was not displaying the selected projects …

Added description and fixed duplicate modal not using project name

---

client/src/components/PdfPrint/PdfFooter.js
client/src/components/PdfPrint/PdfPrint.js
client/src/components/ProjectWizard/WizardPages/ProjectSummary/LandUses.jsx
client/src/components/ProjectWizard/WizardPages/ProjectSummary/MeasureSelected.jsx
client/src/components/ProjectWizard/WizardPages/ProjectSummary/ProjectDetail.jsx

Fixes #1568 Fixes #1747
- Right-align test indicating choice selected for measures
- Temporary fix for footer on PDF where footer overlaps content, but pushing footer information to appear after the content.
- PDF Printout had excessive right-margin around details and measures.
- Horizontally right-align value for Land Uses with numeric fields above and below.
-
- Requested by Bonnie
(none)
<details>
</details>
<details>
</details>

PDF Print - right-align values, temp fix to footer on PDF

---

client/src/components/Layout/ContentContainer.js
client/src/components/Layout/Sidebar.js

…contentContained and sidebarContainer
Fixes #1705
- change flex: "1 1 auto" in ContentContainer.js to flex:1 
- reducing flex basis to 0 makes it so the content doesn't expand when answer takes up space, it adjusts the content within the container 
<details>
</details>
<details>
</details>

1705 fix sidebar width faq page

---

client/src/components/PdfPrint/PdfFooter.js
client/src/components/PdfPrint/PdfPrint.js

Fixes #1757 
- Made it so the PDF print footer appears at the bottom of every page without overlapping
- Justify content to bottom for when the footer is smaller (i.e. no snapshots)
- Footer appears right under the body instead of at the bottom of every page
<details>
</details>
<details>
</details>

Modify the PDF Print format so the footer appears on each page

---

client/src/components/PdfPrint/PdfFooter.js
client/src/components/PdfPrint/PdfPrint.js
client/src/components/ProjectWizard/AffordableEdgeCaseModal.js
client/src/components/ProjectWizard/PackagePanel/RulePackage.js
client/src/components/ProjectWizard/RuleStrategy/RuleStrategy.js
client/src/components/ProjectWizard/RuleStrategy/RuleStrategyLabel.js
client/src/components/ProjectWizard/TdmCalculationContainer.js
client/src/components/ProjectWizard/TdmCalculationWizard.js
client/src/components/ProjectWizard/WizardFooter.js
client/src/components/ProjectWizard/WizardPages/ProjectMeasures.js
client/src/components/ToolTip/ToolTipLabel.js
client/src/components/UI/AriaModal/ModalDialog.js

Fixes #1354
- Implemented Warning Dialog when user chooses 100% affordable housing strategy for project with 25-49 residential units.
-
-
- See Issue #1354
-
-
<details>

1354 affordable housing edge case dialog

---

client/src/components/ProjectWizard/RuleStrategy/RuleStrategy.js
client/src/components/ProjectWizard/RuleStrategy/RuleStrategyList.js
client/src/components/ProjectWizard/RuleStrategy/RuleStrategyPanels.js
client/src/components/ProjectWizard/TdmCalculationContainer.js
client/src/components/ProjectWizard/TdmCalculationWizard.js
client/src/components/ProjectWizard/WizardPages/ProjectMeasures.js
client/src/components/UI/UniversalSelect.jsx

Fixes #1354
- Moved the AffordableHousingEdgeCaseModal calls into RuleStrategy, so previous valueof the drop-down can be restored if the user choose No from the dialog.
-
-
- The UniversalSelect component was not working - it would not pre-select an existing value.  Switched ReactStrategy component back to using standard react select control.
- The previous attempt at the Affordable Housing dialog was unable to revert to the original value if the user selected "No" when prompted.

Fix Affordable Housing edge case

---

client/src/components/Projects/CsvModal.js
client/src/components/Projects/MultiProjectToolbarMenu.js
client/src/components/Projects/ProjectContextMenu.js
client/src/components/Projects/SnapshotProjectModal.js

Fixes #1790
- Swap out MDCamera (aperture shaped) icon for MDCameraAlt (camera shaped)
- Swap FA FileCsv for FA6 FileCsv
- aligned camera to text on the snapshot modal
- Icons were inconsistent with the style guide
<details>
</details>
<details>
</details>

Replace and correct all icons in the project with Material UI icons 

---

client/src/components/Admin/RuleViewContainer.js
client/src/components/ProjectWizard/RuleStrategy/RuleStrategy.js
client/src/components/Projects/FilterDrawer.js
client/src/components/Projects/ProjectsPage.js
client/src/components/UI/UniversalSelect.jsx

Fixes #1817
- See Issue
- See Issue

Fix to UniversalSelect Component

---

client/src/hooks/useGetProjects.js

- Fixes #1808
- Code for permanently deleting projects that are in the trash for over 90 days had a bug that prevented any access to projects that are in the trash.  Fixed.
- Issue #1808

Fixed bug where deleted projects were not displayed on the My Projects Page

---

client/src/components/Faq/ExpandButtons.jsx
client/src/components/Faq/FaqButtonContainer.jsx

Fixes #1798 
- Aligned the expand and collapse icon to the text.
- Switched out the expand all, collapse all, expand, and collapse button to match the design guide.
- Incorrect icons were switched out to the correct icons.
tdm@hackforla.org account was used for testing.
<details>
</details>
<details>
</details>

Aligned and switchout icons for expand and collapse

---

client/src/components/Projects/ColumnHeaderPopups/StatusPopup.js
client/src/components/Projects/ColumnHeaderPopups/VisibilityPopup.js
client/src/components/Projects/ProjectTableRow.js

Fixes #1646
-Kept state in the visibility and status popups.
-Used our own Radio button component and a custom checkbox, instead of Universal Selector.
-Removed "Deleted" keyword from the modified date column
-Added "Deleted" keyword to status column and background color for deleted projects. I'm not particularly attached to this change, but it's an action item in the description for this issue, so I'm including that for now.
In my previous pull request, I'd created too many state/prop items and drilled them through multiple components, creating a lot of entanglement and possible points of failure. This version keeps changes limited to the popup components. It also uses radio buttons and checkboxes instead of dropdowns, keeping it closer to the prototype.

Filters implemented with new state, different selectors

---

client/src/components/Projects/ColumnHeaderPopups/ProjectTableColumnHeader.js
client/src/components/Projects/ColumnHeaderPopups/TextPopup.js
client/src/components/Projects/FilterDrawer.js
client/src/components/Projects/ProjectsPage.js

Fixes #1647
- The `ProjectTableColumnHeader` and `TextPopup` components are now called with a new prop `uniqueValues`, an array that includes sorted unique non-null values from all the currently displayed projects (all pages) for the specific project property.
- uniqueValues is used to populate the dropdown options in a UniversalSelect component, which wraps React-Select in order to provide consistent styling.
- The placeholder text "Search by keyword" was used based on the mockups in #1578.  A search icon is displayed to the left of the placeholder text, using same graphic used in the current search bar input.  Please let me know if a different icon or placeholder text should be used.  
- A new prop was required because the `TextPopup` component didn't have access to project properties …

Implement filtering on Name, Address, Alt# and Created By column headings

---

client/src/components/Projects/ProjectsPage.js

- Fixes #1647
- There was a problem with the implementation. When a filter by text already existed and the popup was opened, the uniqueValues list was based on the sortedProjects, which was already filtered by the previously selected text. This meant that the drop-down list to choose from only included the text strings that already met the previous sort string, so it was not possible to remove the filter or remove characters from the search string. The only way to change the search string was to push "reset", then "apply", then re-open the text popup.
- Fixed by making the uniqueValues based on (unsorted / unfiltered) projects.
-

TextPopup - unique values from projets, not sortedProjects

---

client/src/components/Projects/ColumnHeaderPopups/MultiSelectText.js
client/src/components/Projects/ColumnHeaderPopups/ProjectTableColumnHeader.js
client/src/components/Projects/ColumnHeaderPopups/TextPopup.js
client/src/components/Projects/FilterDrawer.js
client/src/components/Projects/ProjectsPage.js

Fixes #1850
- Implement 2 different styles of column heading filtering for text-based columns
- So designers, PMs and stakeholders can experience two different approaches and make decisions about what to implement
<details>
</details>
<details>
</details>

Implement 2 styles of text filtering

---

client/src/components/Projects/ColumnHeaderPopups/MultiSelectText.js

Fixes #1850
- Make the search for list items on the Text Popup case-insensitive.
-
-

Make text filtering case insensitive

---

server/db/migration/V20240919.1358__fix_fix_default_affordable_housing_selection_1854.sql

Fixes #1854
- Change Affordable Housing strategy to default to "N/A" instead of showing "Select..."
- To be consistent with other drop-downs

Affordable housing selection shoudl default to N/A

---

client/src/components/Projects/ColumnHeaderPopups/TextPopup.js

Fixes #1850
- Center the Reset and Apply buttons horizontally in all column heading popups.
- On Address-style Text Popup, move search icon to the right side of the input, and remove the placeholder text.
- On Name-style TExt Popup, change placeholder text to "Filter"
- Modify the Name-style Text Popup to NOT close the drop-down list as each item is selected from the list.
- Modify the Name-style Text Popup to keep the drop-down list within the boundaries of the popup
- Per Bonnie's request
<details>
</details>
<details>
</details>

Requested Adjustments to TextPopup component

---

client/src/components/Projects/ProjectsPage.js

Fixes #1649
- added "description" to the project properties that are compared against the search input text.  
- changed the "placeholder text" in the Search text box to "Search by Name; Address; Description; Alt#"
- increased the width of the search input box to provide space for longer placeholder text
- To enable users to more effectively search for projects
- To enable testing searches against the description field, I created a new project "Testing Issue 1649" with a description including these words: "GitHub", "repository", "Search", "Text", "hackforla/tdm-calculator"
- Changes to placeholder text was made to conform to the Figma prototype
<details>
</details>
<details> …

Update search logic to match against "description" property 

---

client/src/components/Faq/Answer.jsx
client/src/components/ToolTip/AccordionToolTip.js

Fixes #1797 
- Added launch icons to external links on FAQs and create project page tooltip using Interweave transformer
- External links on the FAQs and the create project page tooltip were missing launch icons to differentiate from internal links
<details>
</details>
<details>
</details>

Add Launch icon to external links 

---

client/src/components/Authorization/UpdateAccount.jsx
client/src/components/Layout/NavBarLogin.jsx
client/src/components/Layout/TdmAuthProvider.jsx
client/src/components/ProjectWizard/TdmCalculationContainer.jsx
client/src/components/Projects/FilterDrawer.jsx
client/src/components/Projects/MultiProjectToolbarMenu.jsx
client/src/components/Projects/ProjectContextMenu.jsx
client/src/components/Projects/ProjectsPage.jsx
client/src/components/Roles.jsx
server/middleware/jwt-session.js

Fixes #1842
- at the server, add new property `expiration` to the `user` object
- at the client, check for expiration in TdmAuthProvider.  If the expiration time has passed, the user account object is set to null, in state, UserContext and local Storage
- updated various components to prevent them from accessing properties of the account object after it has been set to null. 
- Since the expiration time was not checked periodically, the website did not respond promptly when an account expired, and so the user was permitted to initiate actions (such as editing the FAQ) that could not be completed.  
- The solution in this PR involves only the client and so it is not able to detect situations where the user is logged out from a separate browser tab.  A more complete solution would have the …

1842 add expiration date/time to user account

---

client/src/components/Button/Button.jsx
client/src/components/Faq/DeleteFaqModal.jsx
client/src/components/ProjectWizard/NavConfirmDialog.jsx
client/src/components/Projects/CsvModal.jsx
client/src/components/Projects/DeleteProjectModal.jsx

Fixes #1929
- Changed warning buttons with red background to have white text instead of black.
- Changed CSV Download button styles per style guide.
- Changed Share Snapshot button styles per style guide.
- UX Research recommended the changes after testing with users.
<details>
</details>
<details>
</details>

created button variant for error with white text

---

client/src/components/Button/TertiaryButton.jsx
client/src/components/Projects/ColumnHeaderPopups/ProjectTableColumnHeader.jsx
client/src/components/Projects/ProjectsPage.jsx
client/src/hooks/useSessionStorage.js

- Fixes #1683
- Fixes #1981
- Implemented Multi-column sort - see Issue #1981
- Implemented persistence of Filter and Sort settings for user session - see issue #1683
- Per stakeholder and PM request
<details>
</details>
<details>
</details>

Implement My Project multi-column sort, session persistence

---

client/src/components/Layout/ContentContainer.jsx
client/src/components/Layout/ContentContainerNoSidebar.jsx
client/src/components/Projects/ColumnHeaderPopups/ProjectTableColumnHeader.jsx
client/src/components/Projects/MultiProjectToolbarMenu.jsx
client/src/components/Projects/ProjectsPage.jsx
client/src/styles/App.scss

Fixes #1927
- use JavaScript to modify style of the `body` element in `<ProjectTable>`, to prevent page-wide scrolling
- enable scrolling on `div.tableContainer`
- make table headings "sticky" so they are always visible regardless of vertical scroll position
- changes to the zIndex (stacking order) of header and popover so that popovers appear "on top" of the table heading.   
- change minHeight on contentContainer because the previous value did not adjust with user's selection of font size
- At screen widths less than 800px, the toolbar, input field, and button directly above the table become cut off.  Regardless of how scrolling is implemented, the design and implementation of those elements should be revisited to be responsive at smaller screen sizes.  
- When the browser window was …

update classes to prevent cutoff of left side of project table

---

client/package-lock.json
client/src/components/Projects/ColumnHeaderPopups/ProjectTableColumnHeader.jsx
client/src/components/Projects/ColumnHeaderPopups/TextPopup.jsx
client/src/components/Projects/FilterDrawer.jsx
client/src/components/Projects/ProjectTableRow.jsx
client/src/components/Projects/ProjectsPage.jsx

Fixes #replace_this_text_with_the_issue_number
- Added droList and adminNotesList to handle multi-select filtering for DROs and Admin Notes.
- Change  the filter Function in ProjectsPage.jsx to Include DRO and Admin Notes
- Modified the TextPopup.jsx Component to Handle DRO and Admin Notes Filtering
- To support multi-select filtering for DROs and Admin Notes, droList and adminNotesList were added to the criteria
- To enable filtering, modified the filtering function 
- For Dro Column modified the Text Popup to include only the specific values dro can take. 
<details>
</details>
<details>
<summary>Visuals …

1651 filtering sorting dro admin

---

client/src/components/Faq/FaqConfirmDialog.jsx
client/src/components/Faq/FaqView.jsx
client/src/components/ProjectWizard/TdmCalculationWizard.jsx

Fixes #1896 
- Created an FAQ confirm modal that triggers when editing the FAQ page in admin mode
- To confirm if user in admin mode wants to navigate away from the FAQ page after making an eidt
<details>
</details>

1896 communicating unsaved changes faq page

---

client/src/components/ProjectWizard/TdmCalculationContainer.jsx

Fixes #2028
- Fixed a bug  introduced in PR #1988 that caused the symptoms listed in the next section.
- A bug was introduced in PR #1988 that caused the Save Project Button to always be disabled, preventing users from saving changes to projects.
- The same bug also caused the footer on Page 5 of the Calculation Wizard and the PDF Printout to not appear
-
<details>
</details>
<details>
</details>

Fix missing footer on Calculation Summary Page and PDF

---

client/src/components/ProjectWizard/TdmCalculationWizard.jsx
client/src/components/ProjectWizard/WizardPages/Level0Page.jsx
client/src/components/ProjectWizard/WizardPages/ProjectDescriptions.jsx
client/src/components/ProjectWizard/WizardPages/ProjectMeasures.jsx
client/src/components/ProjectWizard/WizardPages/ProjectTargetPoints.jsx
client/src/components/ProjectWizard/WizardPages/ResetButtons.jsx

Fixes #1993 
- Change the "Reset Page" button to "Clear page" on Page 2 & 4
- Add the "Reset Project" & "Clear page" buttons to Page 1 & 3
- UXR recommendation
Screenshots:
<details><summary>Page 1</summary>
</details> 
<details><summary>Page 2</summary>
</details> 
<details><summary>Page 3 with Target Points</summary>
</details> 
<details><summary>Page 3 Level 0</summary>
</details> 
<details><summary>Page 4</summary>
</details>

Implemented changes to reset buttons

---

client/src/components/ProjectWizard/TdmCalculationWizard.jsx

Fixes #2067
- props supporting reset/clear buttons on Page 1 
- Reset Project and Clear Page did not function on Page 1 of the Project Wizard
- Reset Project should clear data from all pages for a new project, or reset to saved state for an existing project.  In either case,  navigate to the first page.

clear page and reset project buttons on page 1

---

client/src/components/Authorization/Login.jsx
client/src/components/ProjectWizard/TdmCalculationContainer.jsx
client/src/components/ProjectWizard/TdmCalculationWizard.jsx

Fixes #2014
- Modified TDM Wizard and container to redirect to login page with the shared snapshots page url stored
- changed response when nothing found in db
- Login page checks for ?url= in url
- the login page should remember that they were trying to navigate to the snapshot, and redirect back to the snapshot path after a successful login.

Redirect shared snapshot to login with redirect url when email does not have access

---

client/src/components/ProjectWizard/RuleInput/ParkingProvidedRuleInput.jsx
client/src/components/ProjectWizard/WizardPages/ProjectTargetPoints.jsx
client/src/components/ProjectWizard/WizardPages/ResetButtons.jsx

Fixes #2065
- Created the function `handleClear` for clearing the "parking spaces provided" input on Page 3, and used that in place of `uncheckAll` which was used to clear inputs on the other project wizard pages
- Page 3 binds the "parking spaces provided" input differently than the other pages/inputs; it uses a state variable 'spacesProvided'.   The existing handler `uncheckAll` updated the rules array but didn't clear `spacesProvided` and so the "parking spaces provided" input was not cleared. 
no visual changes

2065 "Clear Page" button on page3

---

client/src/components/ProjectWizard/RuleInput/ParkingProvidedRuleInput.jsx
client/src/components/ProjectWizard/WizardPages/Level0Page.jsx
client/src/components/ProjectWizard/WizardPages/ProjectDescriptions.jsx
client/src/components/ProjectWizard/WizardPages/ProjectMeasures.jsx
client/src/components/ProjectWizard/WizardPages/ProjectSpecifications.jsx
client/src/components/ProjectWizard/WizardPages/ResetButtons.jsx

Fixes #2099
- Added the prop `rightAlignStyle' for the `ResetButtons` component so that the right margin of the "Clear Page" button could be specified independently on each wizard page.  
- Previously the appearance of the buttons did not match the design depicted in      ,  and the right margin could not be adjusted on a per page basis, because ResetButtons didn't utilize the className prop.  
<details><summary>Before</summary>
</details> 
<details><summary>After</summary>
</details> 
<details><summary>Before</summary>
</details> 
<details><summary>After</summary>
</details> 
<details><summary>Before</summary>
</details> 
<details><summary>After</summary>
</details> 
<details><summary>Before</summary>
</details> 
<details><summary>After</summary>
</details>

Add new prop to align reset buttons

---

client/src/components/ProjectWizard/RuleInput/MultiInput.jsx
client/src/components/ProjectWizard/RuleInput/RuleInput.jsx
client/src/components/ProjectWizard/RuleInput/RuleInputList.jsx
client/src/components/ProjectWizard/RuleInput/RuleInputPanels.jsx
client/src/components/ProjectWizard/TdmCalculationContainer.jsx
client/src/components/ProjectWizard/TdmCalculationWizard.jsx
client/src/components/ProjectWizard/WizardPages/ProjectDescriptions.jsx

Fixes #2066
Also fixes #2067
- The state variable `inputValue` (representing an incomplete AIN number) was moved up to `TdmCalculatorContainer` and renamed `partialAIN` so that it could be cleared by the "Clear Page" button.  
- The `onUncheckAll` function was modified to clear incomplete AIN number
- Previously "Clear Page" and "Reset Project" did not work if an incomplete AIN number was present on Page 1.  This is because an incomplete AIN number was not in the `formInputs` or `rules` and so it was not cleared in the same manner as other inputs 
no visual changes

Fix bug where Clear and Reset do not update the AIN on Page 1 

---

client/src/components/Projects/ProjectTableRow.jsx

- Fixes #2011
- In the Created By column on the My Projects display, show names in lastname, firstname format.
- See Issue
<details>
</details>
<details>
</details>

Display lastname, firstname format for CreatedBy column

---

client/src/components/Projects/ColumnHeaderPopups/ProjectTableColumnHeader.jsx

- Fixes #1996
- Add Icon to column header for the primary sort criterion
- Note that the My Projects page implements a multi-column sort, but the icon only indicates the primary sort column
- See Issue
<details>
</details>
<details>
</details>

Add sort icon to column headers on My Project page

---

client/src/components/Projects/AdminNotesModal.jsx

- Fixes #2068
- Remove Icon from Edit Note button on modal dialog for editing Admin Notes on My Project Page
- See Issue
-
-
Any admin user
<details>
</details>
<details>
</details>

Remove Icon from Edit Note button on modal dialog for edting admin notes

---

client/src/components/ProjectWizard/WizardFooter.jsx
client/src/components/ProjectWizard/WizardPages/ProjectSummary/LandUses.jsx
client/src/components/ProjectWizard/WizardPages/ProjectSummary/MeasureSelected.jsx
client/src/components/ProjectWizard/WizardPages/ProjectSummary/ProjectDetail.jsx
client/src/components/ProjectWizard/WizardPages/ProjectSummary/ProjectInfo.jsx
client/src/components/ProjectWizard/WizardPages/ProjectSummary/ProjectInfoList.jsx
client/src/components/ProjectWizard/WizardPages/ProjectSummary/ProjectSummary.jsx

- Fixes #2051
- Increased minimum font size for all text on the Project Summary Page
- See Issue
<details>
</details>
<details>
</details>

Increase min font size to 16px on Calculation Summary Page

---

client/src/components/ProjectWizard/RuleInput/ParkingProvidedRuleInput.jsx

- Fixes #2052
- Slight change to also limit the number of digits that can be typed into the Provided Parking field on the Target Points page.
- Part of original request for Issue #2052
-
-
<details>
</details>
<details>
</details>

Limit Provided Parking maxlength=7

---

.github/ISSUE_TEMPLATE/bug-report.md

- Removed a lot of the boilerplate text. It's useful the first time the template is used, but becomes an annoyance every time thereafter.
- Reversed the order of the Expected Results and Actual Results. In my experience prior to TDM, the Actual Results always came first. That's more of my personal preference simply out of habit and I think makes sense because it's the order that the developer will experience the bug when following the steps: first they'll see the bug, and then they'll imagine what it's supposed to look like afterward.
- Added "detail" element formatting to put evidence of the defect in screenshot or video format.

Tristan Camacho's proposed changes to the Bug template.

---

client/src/components/Layout/NavBarLogin.jsx

Fixes #2042 
- Made it so warning tooltip on landing page is no longer fixed on scroll
- Removed a prop `lockScroll` from `<Popup>` because that prop only works with modals not tooltips
- Tooltip on landing page was fixed on scroll, it would move with the scroll instead of staying anchored to it's trigger. In this case the `login` link
- The prop cleanup is not user facing, just some cleanup to try to avoid any tech debt
- N/A
<details>
https://github.com/user-attachments/assets/45da98cc-ddcf-41b1-9d2e-4bcf99a91037
</details>
<details> …

fix: warning tooltip no longer fixed | prop cleanup

---

client/src/components/Authorization/SendEmailForm.jsx

Fixes #2047 
- Changed "Email is required" error text to have the color #C3391D
<details>
</details>
<details>
</details>

changed theme color to critical color for error message

---

client/src/components/Authorization/Register.jsx

- Fixes #2152
- Fixes #2045
- Left aligned the error messages on the registration page
<details>
</details>
<details>
</details>

made error messages left aligned on new account page

---

client/src/components/Modals/ActionProjectsCsv.jsx

- Fixes #2142
- Allow clearing the filename
- but if filename is cleared, hide the generate file button, since that would be an error
- See Issue
<details>
</details>
<details>
</details>

Allow clearing CSV file download filename

---

client/src/components/UI/DateRangePicker.jsx

- Fixes #2201
- Prevent calendar from jumping to top of input on screen resize or smaller screens
- bug fix
<details>
https://github.com/user-attachments/assets/1679e26d-0be9-483c-9d82-2163cfe821b8
</details>
<details>
https://github.com/user-attachments/assets/0ec4d2cf-d71d-4c98-975c-2887d81ae35e
</details>
This issue (in theory) was a quick fix. But I had to go one level deeper to find the popover library that `react-datepicker` was using in order to find how to stop that behavior in it's docs: [Floating UI Docs](https://floating-ui.com/docs/getting-started)
While solving this issue I found another that should be a different ticket (if it's something we want to try to fix, it may …

fix: prevent calendar from jumping on small screen heights

---

client/src/components/Projects/ProjectsPage.jsx

- Fixes PR #2200
- Fix filtering by author
- PR #2200 changed the format of the author search criteria for Last Name, First Name, but did not change the filter function to match, so the criteria were entered OK, but the filter bay author was broken and returned no results.

Fix to PR2200

---

client/src/components/ProjectWizard/TdmCalculationContainer.jsx

- Fixes #2129 
- Reduced Parking Supply no longer wipes when `Clear Page` is clicked
- Reduced Parking Supply is calculated based on the user's answer on page 3, so it should stay as long as page 3 has an answer.
<details>
https://github.com/user-attachments/assets/217f2261-8461-4b1c-9a55-38b537339e31
</details>
<details>
https://github.com/user-attachments/assets/05116b5e-0189-428b-8858-6b87ef0e2e1c
</details>

fix: parking strategy 5 does not wipe on clear page click

---

client/src/components/Modals/ActionProjectSnapshot.jsx
client/src/components/Modals/ActionSnapshotRename.jsx

- Fixes #2159
- See Issue
- Also constrained the width of the dialog, as it can get quite wide if the project name is long.
- See Issue
<details>
</details>
<details>
</details>

Change button label from Done to Proceed on 2 Modals

---

client/src/components/ProjectWizard/RuleInput/ParkingProvidedRuleInput.jsx

- Fixes #2154 
- Change parking provided input to be type of number. 
- On chromium browsers this will not allow the user to input any letters. On firefox it will still allow the user to input letters but it will not let them advance (it disables the next and save buttons).
<details>
</details>
<details>
</details>

fix: chromium only - allow only numbers on parking provided

---

client/src/components/Projects/ColumnHeaderPopups/TextPopup.jsx

- Fixes #2043 
- Truncate text on the admin notes popup in the `my projects` page
- Bug fix.
<details>
</details>
<details>
</details>

fix: truncate admin notes

---

client/src/components/ProjectWizard/RuleCalculation/RuleCalculation.jsx
client/src/components/ProjectWizard/TdmCalculationContainer.jsx
client/src/components/ProjectWizard/WizardPages/Level0Page.jsx

- Fixes #2130
- When user clears page 4, it also clears the description of the User-Defined strategy
- It was not being cleared.
<details>
https://github.com/user-attachments/assets/50b96e3d-e20e-4c1d-ba66-a49661b46822
</details>
<details>
https://github.com/user-attachments/assets/b2da01d1-b7b1-4f6c-ac88-1e159ce72711
</details>

When clearing page 4, also clear user-defined strategy comment

---

client/src/components/Projects/ColumnHeaderPopups/StatusPopup.jsx
client/src/components/Projects/ProjectsPage.jsx

- Fixes #2007
- Change the sorting choices for the Status column to "Sort A-Z" and "Sort Z-A", which will sort the possible column values of
"Draft", "Draft (deleted)", "Snapshot", "Snapshot (deleted)" in alphabetical or reverse alphabetical order, respectively.
- Because Bonnie wanted it to work this way
<details>
</details>
<details>
</details>

Change status column sort labelling

---

client/src/components/Modals/WarningProjectReset.jsx
client/src/components/ProjectWizard/TdmCalculationWizard.jsx

- Fixes #1942 
- Added a warning modal when user clicks on reset project while in wizard
- feature requested so that users don't accidentally miss-click and lose their entire project.
<details>
- nothing visual happens, it just instantly resets the project
</details>
<details>
</details>

feat: add warning modal when reset project is clicked

---

client/src/components/Layout/ContentContainer.jsx
client/src/components/Roles.jsx

- Fixed #2053
- Added sticky to header of roles table. Visible only in security admin role login > Security page
- Bug fix request so users can see what information of roles if a long list is presented
Must use: Security Admin
Can see credentials on 1pass
<details>
https://github.com/hackforla/tdm-calculator/issues/2053
</details>
<details>
[![image](Paste_Your_Image_Link_Here_After_Attaching_Files)](https://github.com/user-attachments/assets/cd5dc922-bf15-4d83-8495-19b9b8b19d15)
</details>

Fixed: Security Roles table header does not stick to the top of the viewport

---

server/db/migration/V20250330.1839__allow_users_to_see_shared_snapshots_on_myprojects_2257.sql

- Fixes #2257
- On My Projects page for non-admin users, include snapshots belonging to other users that are shared with them.
- Requested by Issue
Need to use any account that has had one or more snapshots shared with it (e.g., tdm-dev+user2@hackforla.org on the dev environment)
<details>
</details>
<details>
</details>

Allow users to view shapshots shared with them on My Projects Page

---

client/src/components/Projects/ProjectsPage.jsx

- Fixes #2182
- Change `verticalAlign: "middle"` to `verticalAlign: "top"` for the data cell in the table body  
- When a project row has more than one line of text within a column, elements in most columns become vertically center-aligned. For readability reasons, elements should instead be top-aligned.
<details>
<summary>Visuals before and after changes are applied</summary>
</details>

2182 top-aligned data cell within project rows

---

client/src/components/ProjectWizard/TdmCalculationContainer.jsx
client/src/components/ProjectWizard/TdmCalculationWizard.jsx
client/src/components/ProjectWizard/WizardFooter.jsx
client/src/components/ProjectWizard/WizardPages/ProjectSummary/ProjectSummary.jsx
server/db/migration/V20250331.2105__fix_to_2257.sql

- Fixes #2314
- Fixed bug where a user (admin or not) viewing a snaphot in the Wizard could navigate away from page 5 and start editing the calclulation.
- See issue
<details>
See Issue
</details>
<details>
</details>

Snapshot should not allow navigating off p5

---

client/src/hooks/useCheckedProjectsStatusData.js
server/db/migration/V20250404.1628__fix_to_2163.sql

- Fixes #2163
- Modified Project_Hide stored procedure to allow changing dateHidden for projects that dont belong to the user.
- To complete issue #2163
<details>
</details>
<details>
</details>

Allow non-owner of project to hide

---

client/src/components/Projects/ProjectTableRow.jsx
client/src/components/Projects/ProjectsPage.jsx

- Fixes #2181
- Remove "Date" in "Date Admin Saved" as suggested by UX
- Change the `colWidth` of "Visibility", "Created On", "Last Saved", and "Admin Saved"
- Change the content of "Created On" data cell to left aligned as in Figma 
- Change `width: "135rem"` to `width: "100%"` for the tableAdmin and table to make the column widths expand to fill the entire available horizontal space
- To make the filter icon sizes consistent 
<details>
</details>
<details>
</details>

2181 Change colWidth to make the filter icon sizes consistent

---

.github/scripts/find-label-in-gh-issue.cjs

- Fixes #2342 
- this changes the way the shell reads the PR to not confuse variables enclosed in backticks with shell execution commands.
- it now creates an ephemeral txt file that it will read instead of reading the PR directly which will get cleaned up when the worker spins down.
- this new script change also makes it case insensitive when looking for the phrases before the issue number at the top of the PR.
- BELOW IS JUST A TEST OF A PR THAT FAILED BEFORE, PLEASE IGNORE THE CONTENT. IT IS FOR TESTING PURPOSES ONLY
- Remove "Date" in "Date Admin Saved" as suggested by UX
- Change the `colWidth` of "Visibility", "Created On", "Last Saved", and "Admin Saved"
- Change the content of "Created On" data cell to left aligned as in Figma 
- Change `width: "135rem"` to `width: "100%"` for the …

fix: ping designers if role includes front-end

---

client/src/components/UI/UniversalSelect.jsx

- Fixes #1897 
- Added 8px padding to dropdown field and options on these pages: 
[Projects page](http://192.168.1.145:3000/projects )  and [Page 4](http://192.168.1.145:3000/calculation/4/0).  
- To improve the readibility of dropdown options and reduce visual clutter.
<details>
</details>
<details>
</details>

1897 Add padding to dropdowns to match the style guide

---

client/src/components/ProjectWizard/WizardPages/DiscoverTooltips.jsx

- Fixes #2176 
- Delete `paddingBottom: 1em` and `left: 22.5px` from useStyles in `DiscoverTooltips.jsx`
- The `paddingBottom` is unused because the `padding: 1em` already includes it. 
- Make Page 1/5 be fully visible. The smaller screen looks better after deleting the left position in CSS.
- You need to log in with TDM user account. 
- Decrease the browser's viewport width to 900px.
<details>
</details>
<details>
</details>

2176 remove paddingBottom and left from useStyles.

---

client/src/components/Authorization/Logout.jsx
client/src/components/Projects/ProjectsPage.jsx
client/src/helpers/Constants.js

- Fixes #2315 
- moved sessionStorage keys for sort/filter settings from ProjectsPage component to helpers/Constants
- remove items from sessionStorage upon logout
- Filters should not persist across multiple logins from different users

2315 Fix project filters persisting across logins

---

client/src/components/Layout/Header.jsx
client/src/components/Layout/NavBar.jsx

- Fixes #2173 
- Changed hamburger menu trigger from 768p to 900px
- Changed spacing in navbar and header
- Updated `max-height` of open menu from hardcoded value to `fit-content` 
- When the viewport width becomes less than the combined length of all the navigation bar buttons but greater than 768px, the My Account and Logout buttons aren't fully visible and therefore cannot be accessed without the user changing the viewport width.
- `Logout` wasn't visible when the menu was open. [The original value](https://github.com/hackforla/tdm-calculator/pull/327) was from when there were fewer links.
<details>
</details>
<details>
Changes show two different viewport sizes that now display …

Adjust spacing of header and navbar for smaller screens

---

client/src/components/Feedback/ProjectList.jsx

- Fixes #2318
- Centered the "Select Relevant Projects" table in the Feedback 
- Requested by #2318
<details>
<summary>Visuals before and after changes are applied</summary>
</details>

center select relevant projects table

---

client/src/components/Authorization/Login.jsx

- Fixes #2399  
- Updated the `Continue Without Saving` button in `client/src/components/Authorization/Login.jsx` to use the `secondary` variant.
- Removed the `color="colorDefault"` attribute from that button.
- The button was not matching the secondary button style defined in our design system.  
- This change ensures the outline, typography, padding, and hover state conform to spec.
N/A (no new temporary account required)
<details>
Before - Continue Without Saving Button
(RC: contributor uploaded an "after" image, I've replaced it with the correct "before".)
`![Screenshot From 2025-04-18 11-34-18](https://github.com/user-attachments/assets/3347afb1-8ffb-41ce-81d8-8ac87c57f13a)`
</details>
<details>
<summary>Visuals after changes are …

fix(login): apply secondary style to 'Continue Without Saving' button

---

client/src/components/Authorization/Login.jsx

- Fixes #2414
- Change Login page to use standard primary and secondary styles.
- See Issue
<details>
</details>
<details>
</details>

Make Login screen use standard button styles

---

client/src/components/Projects/ProjectsPage.jsx

- Fixes #2174 
- Add an outer div to allow flex wrap. 
- so the Reset Filters/Sort button is fully visible when the viewport width is less than 890px
angelawlee07@gmail.com
<details>
)
</details>
<details>
)
)
</details>

Make Reset Filters button visible on small-width screens

---

client/src/components/ProjectWizard/RuleInput/RuleInput.jsx

- Fixes #2352
- See issue
- See issue
<details>
Appearance after entering condo units, then tabbing through the required parking (note that keyboard focus is on the next input)
</details>
<details>
Appearance after entering condo units, then tabbing through the required parking (note that keyboard focus is on the next input)
</details>

Fixed bug in RuleInput to show val error when tabbing through reqd field

---

client/package-lock.json
client/src/components/Faq/CategoryInputContainer.jsx
client/src/components/Faq/FaqButtonContainer.jsx
client/src/components/Projects/MultiProjectToolbarMenu.jsx

- Fixes #2443 
- Fixed the color of the disabled print and visibility icon in Firefox browser.
- The icon colors were darker than the trashcan icon, and needed the color to be consistent.
tdm@hackforla.org account was used for testing.
<details>
</details>
<details>
</details>

fix print and visibility icon color in firefox

---

client/src/components/Faq/Answer.jsx
client/src/components/UI/Quill.jsx
client/src/styles/AdminQuill.scss

- Fixes #2484 
- Add styling to keep the applied indentation on the page
- Add styling to keep consistent font size in the Quill editor and on the page
- Add styling to prevent additional lines being added above lists when the Quill editor is pressed again and again
- Add styling to keep the "Tooltip" input box a similar size to the dropdown below it 
- So that the page works as expected and looks orderly.
<details>
</details>
<details>
</details>

Update Styling for the FAQ Answers

---

client/src/components/ProjectWizard/RuleInput/ProjectLevelRuleInput.jsx
client/src/components/ProjectWizard/WizardPages/ProjectSpecifications.jsx
client/src/services/tdm-engine.js
server/db/migration/V20250430.1543__conditionally-reqd_rules_2467.sql

- Fixes #2467
- Made required fields on Page 2 "conditionally" required, i.e., required only if they are applicable because the related input rule has a value.
- See Issue
<details>
</details>
<details>
</details>

Allow for an set up conditionally required rules

---

client/src/components/Projects/ProjectsPage.jsx
client/src/components/UI/UniversalSelect.jsx

- Fixes #2415 
- Added `isSearchable={false}` by default
- Added `maxMenuHeight={60px}` to make the styling look good.
- The search feature is unnecessary. For the future, if you want to enable the search feature, add the `isSearchable` prop in the `<UniversalSelect ... />` component.
- `maxMenuHeight`: Prevents the dropdown menu from overlapping the footer and creating white space below it.
- Need to login with TDM account.
- Navigate to "My Projects" in the navbar.
<details>
</details>
<details>
</details>

2415-fix-pagination-dropdown-menu.

---

client/src/components/Modals/ActionProjectsCsv.jsx
client/src/components/Projects/MultiProjectToolbarMenu.jsx
client/src/components/Projects/ProjectTableRow.jsx
client/src/components/Projects/ProjectsPage.jsx

- Fixes #2508 
- Tab styling:
- Moved tabs to the right side of the page
- Updated tab dimensions to match design
- Added gray background on hover, white background for inactive tab
- Updated header marginTop
- Moved tabs up to be in line with My Projects header
- Table header:
- Update column header from Date Trashed to Date Deleted
- Update table header color
- Moved Restore button to the right of Reset Filters/Sort button
- Revise radio buttons/filtered options for CSV download
- Updated margin between page nav buttons and footer (by updating tableContainer height)
- Follow-ups to #2375 (design updates made after initial handoff)
<details>
active projects:
deleted projects:
</details>
<details>
<summary>Visuals after changes are …

2508 Additional project tab designs

---

client/src/components/ProjectWizard/TdmCalculationContainer.jsx

- Fixes #2448
- Disable Residential Package on Strategies Page when no parking is provided
- The Residential Package cannot be applied when no parking provided, since the package includes the Pricing/Unbundling strategy which cannot be used if there is no parking to Price/Unbundle.
(any)
<details>
</details>
<details>
</details>

Disable Residential Pkg if no parking provided

---

client/src/components/Button/Button.jsx
client/src/components/Button/NavButton.jsx
client/src/styles/theme.js

- Fixes #2524
Changed hover states for the following Button component variants:
- **Primary**
- Background color is now lighter green (added to theme.js as `colorPrimaryDisabled`)
- Text is now Gray color from theme
- **Secondary**
- Border color is now lighter than active state
- Text is now Gray color from theme
- **Tertiary**
- Text is now Gray color from theme
- Note: the Figma designs do not have a black border on this variant, so I removed that as well
- **Warning**
- Now uses lighter red background color (added to theme.js as `colorCriticalDisabled` )
For NavButton component:
- Background color is now lighter green (same `colorPrimaryDisabled` color as Button component)
- Arrows are now Gray color from theme
- Note: I didn’t see the secondary variant being used anywhere
For all of …

2524 Update button disabled states

---

client/src/components/Projects/ProjectsPage.jsx

- Add back InfoSnapshotSubmit component to ProjectsPage. 
- The success modal wouldn't open after the warning snapshot submit without this component on the projectpage. Adding this back to get it working again. 
<details>
</details>
<details>
</details>

Add back InfoSnapshotSubmitted component to ProjectPage.jsx

---

client/src/components/ProjectWizard/WizardSidebar/SidebarPointsPanel.jsx
server/db/migration/V20250717.1731__feature-flag-for-sidebar-style_2594.sql

- Fixes #2594
- Implemented a feature flag to switch between two different styles of wizard Sidebar, called "LEGACY" and "DIAL"
- So the UX Research team can have different versions of the sidebar to show for user testing, and allow us to easily switch between the two styles without having to re-deploy the application by editing a value in the Config database tablse.
<details>
</details>
<details>
</details>

Feature flag for sidebar style

---

client/src/components/Button/Button.jsx
client/src/components/Button/NavButton.jsx

- Fixes #2571 
- I added an aria-label to the navigation buttons in the Create Project pages
- To fix an accessibility error found by the WAVE tool
Visually the website looks the same, but now screen readers can pick up the navigation buttons. Below I've added screenshots of what the WAVE accessibility tool picks up.
<details>
</details>
<details>
</details>

Fix accessibility error in the Create Project pages navigation buttons

---

server/db/migration/V20250820.1934__update_calculation_rule_names_parkcondo_sftradeschool.sql

- Fixes #2545 
- Running this migration revises the text on two fields on the 2nd page of the calculator
-
<details>
</details>
<details>
</details>
Once the PR has been approved, we have to run the migration on shared DB

fix: revise text on page 2 of calc
