client/src/App.js
client/src/components/Login.js

Login is having issues on Heroku. It works fine on local environment. Testing...

testing async functions

---

Contributing.md
README.md
client/src/components/Admin.js
client/src/components/Faq.js
client/src/components/FaqAdd.js
client/src/components/FaqList.js
client/src/components/FaqView.js
client/src/services/faq.service.js

FAQ Front-End is displayed on "Admin" page where a list of FAQs are rendered.
Depending if a user is an admin, add/update/delete functionality will display.
Code follows style guidelines.
All manual tests all pass.
Comments left in place are for future connections (i.e. checking if user is an admin)

Added first draft of Git instructions and FAQ front-end

---

client/src/components/About.js
client/src/components/ConfirmEmail.js
client/src/components/ContactUs.js
client/src/components/Login.js
client/src/components/Register.js
client/src/contexts/Toast/Toast.js
client/src/contexts/Toast/withToastProvider.js
client/src/services/account-service.js

Utilized the useToast context to add toast messages to Registration, Login, and ConfirmEmail components.  Minor updates to toast css.
Relevant to issues: 
#123 (utilized useToast context), 
#44 (Front-End User Notifications to replace console.log)
#71 (Front-End User Notifications to replace console.log)

Replaced console logs with toasts for Registration, Login, ConfirmEmail

---

client/src/components/Login.js

Reverts hackforla/tdm-calculator#153

Revert "Push to /login instead of /admin if login successful"

---

client/src/components/Login.js
client/src/components/Register.js
client/src/styles/App.scss
client/src/styles/AuthForms.scss
client/src/styles/_partials.scss
client/src/styles/_variables.scss

#71 #50 
- Added Continue without saving button with basic css
- Reorganized/updated some of the shared button/links/inputs css files (_partials.scss, _variables.scss, AuthForms.scss, App.scss) 
- Updated language to match figma
- Added warning when hovering over "continue without saving button"

Added continue without saving button & updated some text/css

---

client/src/components/Login.js
client/src/components/Register.js
client/src/styles/AuthForms.scss

Removed stay signed in checkbox 
Removed toasts, 
Added auth error msgs under submit button; 
Changed color of invalid form inputs from blue to red
#71

Removed toasts, added auth error msgs under submit button; removed checkbox

---

app/services/account.service.js
client/src/App.js
client/src/components/Login.js
client/src/components/ResetPasswordRequest.js
client/src/services/account-service.js

Request password reset works. Fixed login bug.

Request password reset works. Fixed login bug.

---

app/services/account.service.js
app/services/sendgrid-service.js
client/src/App.js
client/src/components/ResetPassword.js
client/src/components/ResetPasswordRequest.js
client/src/services/account-service.js

I didn't add the side bar image on the components. Will look into making a reusable one because it is currently being created separately on each view.

Password reset works and redirects to login after completion.

---

client/src/App.js
client/src/components/Header.js
client/src/components/NavBar.js

Changes made:
- When logged in, have name styled white, positioned to the right on header
- Made <Route> syntax consistent, no functionality should be changed
- Used a fragment to remove an unneeded nested div
Fixes issue(s):
#175

Styled name white when logged in

---

client/src/components/LandingPage/LandingPageSectionEnd.js
client/src/components/LandingPage/LandingPageSectionHeroImage.js
client/src/components/NavBar.js
client/src/components/TdmCalculationContainer.js

- Added componentDidUpdate to track browser address query string and load  the proper wizard page when browser navigation (back/forward) are used.

set routes to work correctly using browser navigations

---

client/src/App.js
client/src/components/Header.js
client/src/components/NavBar.js
client/src/components/TdmCalculationContainer.js

#201 
Added useState to App.js to set/get a boolean variable (isCreatingNewProject, setIsCreatingNewProject)
pass down getter variable to Header > Navbar
pass down setter variable to TDM Calculation Container

Conditionally render New Project Link in Nav

---

client/src/components/ProjectWizard/TdmCalculationWizard.js
client/src/components/ProjectWizard/WizardReviewPanel.js
client/src/components/ProjectWizard/WizardRuleInput.js
client/src/components/ProjectWizard/WizardRuleInputPanels.js
client/src/components/ProjectWizard/WizardRuleStrategyPanels.js
client/src/components/Projects.js
client/src/styles/Calculation.scss
package.json

Reset page option styled to specifications of @ExperimentsInHonesty & @KPHowley .

styled reset page

---

client/package-lock.json
client/package.json
client/src/components/About.js
client/src/services/tdm-engine.js
package-lock.json
package.json

Update version # in package.json files and About page. Also, modify tdm-engine.js to ignore rule codes that are stored in a project, but no longer part of the rule set. (This allowed us to drop a few rules that are obsolete).

Bump version #, fix for non-existent inputs in saved project

---

client/src/components/Projects.js

#179 
Finished "Allow specifying a sort criteria (by created date, modified date, name, user)"

Enable project data table sort by column

---

client/src/components/ProjectWizard/WizardPages/ProjectSummary.js
cypress/integration/project-test-cases/beatrice-building.spec.js
cypress/integration/project-test-cases/clarendon-apartments.spec.js
cypress/integration/project-test-cases/fountain-apartments.spec.js
cypress/integration/project-test-cases/jewish-family-service.spec.js
cypress/integration/project-test-cases/marina-towers-village.spec.js
cypress/integration/project-test-cases/victory-hotel.spec.js

Added Cypress Tests for 7 Example Test Cases

---

app/controllers/account.controller.js
app/routes/account.routes.js
app/services/account.service.js
client/src/App.js
client/src/__snapshots__/storybook.test.js.snap
client/src/components/Authorization/ConfirmEmail.js
client/src/components/Authorization/Login.js
client/src/components/Authorization/Register.js
client/src/components/Authorization/ResetPassword.js
client/src/components/Authorization/ResetPasswordRequest.js
client/src/components/NavBar.js
client/src/components/ProjectWizard/TdmCalculationWizard.js
client/src/components/Roles.js
client/src/components/TdmCalculationContainer.js
client/src/services/account.service.js
middleware/jwt-session.js
package-lock.json
package.json

Add page for security admin

---

client/src/components/ProjectWizard/TdmCalculationWizard.js

-Fixes issue of projectID showing as undefined in the route.
-Fixes issue of not being able to start a new project

fixes routing issue that creates undefined projectID

---

client/src/App.js
client/src/components/About.js
client/src/components/Admin.js
client/src/components/Authorization/Login.js
client/src/components/Footer.js
client/src/components/ProjectWizard/SidebarPoints/SidebarPoints.js
client/src/components/ProjectWizard/TdmCalculationWizard.js
client/src/components/Projects.js
client/src/components/Sidebar.js
client/src/styles/Calculation.scss

adds footer, resizes sizebar based on screen size, moves sidebar to the top on smaller screens if it has content to display, as in the Wizard.
closes #258

Issue 258 responsiveness

---

client/src/components/ProjectWizard/TdmCalculationWizard.js
client/src/components/ProjectWizard/WizardPages/ProjectMeasures.js
client/src/components/TdmCalculationContainer.js

Fixes  problems with enabling/disabling the Commercial Package Button related to the recent changes concerning the Education, Marketing and Outreach strategy.
Fixes #221

Fix issue 221

---

client/src/components/ProjectWizard/SidebarPoints/SidebarPoints.js

Show Target Points, Earned points as blank if 0 on sidebar

---

client/src/components/Footer.js
client/src/components/ProjectWizard/TdmCalculationWizard.js
client/src/styles/Calculation.scss
package-lock.json
package.json

Add styling changes and nodemon

---

app/controllers/project.controller.js
app/routes/project.routes.js
app/services/project.service.js
client/src/App.js
client/src/components/NavBar.js

An admin user should be able to view all Projects on the Projects page.
A non-admin user should only be able to view their own projects.
Implement these rules at the Web API level.

User can only retrieve and/or edit their own projects

---

app/routes/calculation.routes.js
client/src/__snapshots__/storybook.test.js.snap
client/src/components/ProjectWizard/RuleCalculation/RuleCalculation.js
client/src/components/ProjectWizard/RuleCalculation/RuleCalculationList.js
client/src/components/ProjectWizard/RuleCalculation/RuleCalculationPanels.js
client/src/components/ProjectWizard/WizardPages/ProjectSpecifications.js
client/src/components/ProjectWizard/WizardPages/ProjectTargetPoints.js
client/src/services/tdm-engine.js

319 change wizard page 3 headings

---

client/src/components/Header.js
client/src/components/NavBar.js
client/src/components/NavBarLogin.js

Made navbar responsive.
-reduced spacing between navbar elements at 900px
-navbar collapses into hamburger menu at 768px;
-navbar transitions based on max-height, this was done for simplicity since there could be a variable number of elements in the navbar. Max-height is set to 301.6px since this that is the current calculated height with all possible elements. This will be an issue if more elements are added.
closes #301

Louis issue 301 responsive navbar

---

client/src/components/ProjectWizard/RuleInput/RuleInput.js

reduced input width on project specification page.
closes issue #356

change input width

---

client/package-lock.json
client/src/components/ProjectWizard/WizardPages/ProjectTargetPoints.js
package-lock.json

increased width to 800px per the figma design

re-adding styles

---

client/src/components/ProjectWizard/WizardPages/ProjectSummary.js

Changed labels to use rule names rather than hard-coded strings.
Fixes #364

#364 final summary ratio wording change

---

cypress/integration/project-calculations-no-auths/barrington-condos.spec.js
cypress/integration/project-calculations-no-auths/beatrice-building.spec.js
cypress/integration/project-calculations-no-auths/clarendon-apartments.spec.js
cypress/integration/project-calculations-no-auths/fountain-apartments.spec.js
cypress/integration/project-calculations-no-auths/jewish-family-service.spec.js
cypress/integration/project-calculations-no-auths/marina-towers-village.spec.js
cypress/integration/project-calculations-no-auths/victory-hotel.spec.js
cypress/integration/project-crud-with-auths/project-crud-with-auths.spec.js
cypress/support/commands.js

Various updates related to new changes introduced after the tests were initially merges, mainly related to removal of the land use page.

Update tests after land use page removal

---

client/src/components/ProjectSinglePage/TdmCalculation.js
client/src/components/ProjectWizard/TdmCalculationWizard.js
client/src/components/SwitchViewButton.js

Changed Button Names to switch between Wizard and Single Page Views
adjusted button height slightly to accommodate longer names on smaller sized screens.
closes issue #361

change button names, adjust button height to fit content

---

client/src/components/ProjectWizard/SidebarPoints/ToolTip.js
client/src/components/ProjectWizard/SidebarPoints/ToolTipIcon.js
client/src/components/ProjectWizard/WizardPages/ProjectMeasures.js

- standardized question icons from font awesome in both sidebar and project measures page
- removed onclick tooltip popup from sidebar
closes #382

Fix question icon

---

client/package-lock.json
client/package.json
client/src/components/ProjectWizard/SidebarPoints/ToolTip.js
package-lock.json
package.json

Include this pull request for release.
https://github.com/hackforla/tdm-calculator/pull/387

Hotfix 0.2.8

---

client/package-lock.json
client/package.json
client/src/components/ProjectWizard/RuleStrategy/RuleStrategyList.stories.js
client/src/components/ProjectWizard/RuleStrategy/RuleStrategyPanels.stories.js
package-lock.json

This resolves all backend vulnerabilities and frontend ones except for 6. The 6 are 2 dependencies in storybook and react-scripts, which are not used in the actual app.
resolves #287
resolves #336

Fix npm package vulnerabilities

---

.gitignore
cypress.json
cypress/support/commands.js

Disabled videos and screenshots generation.
Added videos and screenshots folders to gitignore.
Closes #383

Disable cypress videos and screenshots

---

client/src/components/Header.js

Fixed Redirect bug when logging out.
closes #399

Redirect to Login Screen on Logout

---

.deployment
client/src/components/ProjectWizard/WizardPages/ProjectSummary.js

Closes #404 
Note: Also requires small database change - put in Database Scripts file for now, but might go into datbase migration file if we are ready.

Change Caption on Summary Page to Baseline Parking

---

client/package-lock.json
client/package.json
client/src/components/ProjectWizard/RuleInput/RuleInput.js
package-lock.json

Masked input for AIN, Label as Link

---

client/src/components/ProjectWizard/WizardPages/ProjectSpecifications.js

Fixes [Issue #409](https://github.com/hackforla/tdm-calculator/issues/409)
Edit: adding image of change

add subtitle to project specifications page

---

client/package-lock.json
client/package.json
doc/Contributing.md
doc/deployment.md
doc/development.md
doc/localdatabase.md
doc/releases.md
doc/testing.md
docker-compose.yml
server.js

This is a start on re-arranging the documentation. The Docker scripts are a work in progress.

Work on docker documentation

---

client/src/components/NavBar.js

Updated route for "create project" button within the NavBar.

---

client/src/components/Projects.js

Quick update to PR [480](https://github.com/hackforla/tdm-calculator/pull/480)
Please let me know there can be improvements to the logic

fix error for user with no projects on projects page

---

db/migration/V0005__update_descriptions_and_points.sql

closes #476 
I also updated the description for the encouragement program because there was random '>' at the end. So I just removed it.

Update strategy descriptions and point values #476

---

app/services/tedious-pool.js
client/src/components/ProjectWizard/RuleInput/RuleInput.js
db/migration/V0006__update_land_uses.sql

Re-organize the project inputs per Issue #494
Add inputs for Middle and High Schools per Issue #452 
Modify level calculation per Issue #443
Add checkbox input for Affordable Housing, per Issue #451

Changes to input rules and level calculation

---

client/src/components/ProjectWizard/RuleCalculation/RuleCalculation.js
client/src/components/ProjectWizard/RuleCalculation/ToolTip.js
client/src/components/ProjectWizard/RuleCalculation/ToolTipIcon.js

added tooltip for Citywide Parking Baseline

---

db/migration/V0008__delete_obsolete_strategies_478.sql

Delete obsolete strategies #478

---

db/migration/V0006__update_land_uses.sql

You will need to run `npm run flyway:repair" and then `npm run flyway:migrate` to apply this change to any existing local database.

Fix to migration V00006

---

db/migration/V0014__add_new_strategies_479.sql
docs/local-database.md
package.json

#479
- ADD TELEVISITS (PTS & STRATEGIES)
- ADD MOBILITY INVESTMENT (PANEL, PTS & STRATEGIES)  1) Alignment Improvements 2) Mobility Management 
- UPDATE EARNED POINTS CALCULATION 
Note:
Televisits is part of the "Telecommute" Calculation Panel. There is originally only one strategy in/called "telecommute." This should probably change to differentiate the "telecommute" strategy from the higher level "telecommute" panel/section.

Add new strategies and update local-database.md #479

---

client/src/components/ProjectWizard/RuleInput/RuleInput.js
client/src/components/ProjectWizard/WizardPages/ProjectMeasures.js
client/src/components/TdmCalculationContainer.js
db/migration/v0015__school_input_and_encouragement.sql

497 trip reduction

---

client/src/components/ProjectWizard/RuleInput/RuleInputPanels.js

Fix vertical responsiveness of loading icon #392

---

db/migration/V0017__land-use-calculations.sql

Update land uses and parking subtotal fornulas

---

client/src/components/ProjectWizard/RuleStrategy/RuleStrategy.js
client/src/components/ProjectWizard/WizardPages/ProjectMeasures.js
client/src/components/TdmCalculationContainer.js
db/migration/V0020__fixes_to_land_use_exclusions.sql

Separate Medical Inputs for Hospitals and Convalescent

---

db/create-migration
db/flyway-config.js
docs/local-database.md

And deleted excess comments/lines of code in flyway-config

Add a create-migration script that will generate .sql migration file

---

db/migration/V8192020.5445__fix_spelling_of_bike_parking_label.sql

Fix spelling of Bike Parking msg

---

client/src/components/ProjectWizard/TdmCalculationWizard.js
client/src/components/ProjectWizard/WizardPages/ProjectMeasures.js
client/src/components/TdmCalculationContainer.js
db/migration/V8262020.5171__bike_parking_dont_initialize_519.sql

Initialize Bike Parking When user navigates to Pg 4

---

client/src/components/ProjectWizard/WizardPages/ProjectTargetPoints.js
client/src/components/Projects.js
client/src/components/TdmCalculationContainer.js

Fix useEffect hook dependency in Projects.js

---

docs/releases.md

Rename master branch to main

---

client/package-lock.json
client/package.json
package-lock.json

Update npm packages

---

.github/workflows/docker.yaml
db/flyway-config.js
db/migration/V0008__delete_obsolete_strategies_478.sql
db/migration/V0012__put_warehouse_calculation_panel_back_478.sql

Also fixed historical db migrations that wouldn't run in sequence properly.

Add main branch to github action

---

client/src/App.js
client/src/components/Footer.js
client/src/components/PrivacyPolicy.js
client/src/components/TermsAndConditions.js

I created a page for "Terms and Conditions" and implemented a functional footer link. #539

Created page for Privacy Policy and implemented a functional footer link

---

client/src/components/Button/NavButton.js

Add disabled to NavButton

---

client/src/components/Button/SwitchViewButton.js
client/src/components/ProjectWizard/TdmCalculationWizard.js

I hid the "Switch to Single Page View" button. #567

Hide "Switch to Single Page View"

---

client/package-lock.json
client/src/components/ProjectWizard/TdmCalculationWizard.js
client/src/components/ProjectWizard/WizardPages/ProjectMeasures.js
client/src/components/ProjectWizard/WizardPages/ProjectPackages.js
client/src/components/TdmCalculationContainer.js

First cut at Issue #528 implementation

Make packages unselectable

---

db/migration/V20201010.1506__edit_choices_for_strategy_affordable_577.sql

Fixes 577. Requires running database migrations

Change Tier 1 to Tiers 1-3 in Aff Housing drop-down

---

db/migration/V20201010.1554__modify_mandatory_tripl_reduction_strategy_576.sql

Closes #576 Require database migrations to be run for deployment

Changes to Trip Reduction Strategy Name and Points

---

client/src/components/ProjectWizard/RuleInput/RuleInput.js
client/src/components/ProjectWizard/RuleStrategy/RuleStrategy.js
client/src/components/ProjectWizard/RuleStrategy/RuleStrategyList.js
client/src/components/TdmCalculationContainer.js
client/src/services/tdm-engine.js
db/migration/V20201010.1611__adjust_strategy_rules_585.sql

Adjust strategies per Issue 585

---

client/src/components/ProjectWizard/RuleStrategy/RuleStrategy.js
client/src/components/ProjectWizard/TdmCalculationWizard.js
client/src/services/tdm-engine.js

Fix client-side validation for minValue

---

db/migration/V20201011.1351__revise_special_use_program_levels_582.sql

Closes #582 . Requires DB Migration.

Modify Project Level Calculation for Auditoriums

---

client/package-lock.json
client/package.json
package-lock.json
package.json

First attempt to fix github workflow

upgrade to react-scripts@4.0.0

---

client/src/components/ProjectWizard/TdmCalculationWizard.js

Removed conditionals that prevented save button and timestamp from appearing on all of the project pages. Now save buttons and timestamps appear on all the create project pages.

603 add save button

---

client/src/components/ProjectWizard/RuleInput/RuleInput.js
docs/contributing.md
docs/deployment.md
server/db/migration/V20201030.1748__rule_adjustments_601_619_616_617.sql

Fixes to 601, 616, 617, 619

---

client/src/App.js
client/src/components/Button/Button.js
client/src/components/ProjectWizard/TdmCalculationWizard.js
client/src/components/ProjectWizard/WizardPages/ProjectSummary.js
client/src/components/TdmCalculationContainer.js
client/src/contexts/Toast/Toast.js
client/src/services/tdm-engine.js

Trying to fix a number of related bugs:
Fixes #628 The Save button should only be enabled if
- The user is logged in
- The project is new OR the logged in user created an existing project
- There are no validation errors,
- The project is new OR an existing project with changes.
Fixes #565 When a project is saved, update the last updated time on the project, stay on the same project on the same page, and display the Saved Project Toast towared the bottom-center of the screen.
Also, when a project is save, do not display the dialog asking if the user wants to discard their changes.

Fix logic for enabling Save button

---

client/src/components/NavBarToolTip.js

Tooltip text updated

---

client/src/components/ProjectWizard/TdmCalculationWizard.js

603 Added Page number to bottom of wizard. Displays '5/5' when it's level 0, 3/5 displays on both the 'calculate tdm target points' page and conditional 'bonus packages' page.

603 add page num to wizard

---

client/src/App.js
client/src/components/Header.js
client/src/components/NavBar.js
client/src/components/NavBarLogin.js
client/src/components/Pagination.js
client/src/components/ProjectWizard/TdmCalculationWizard.js
client/src/components/ProjectWizard/WizardPages/Level0Page.jsx
client/src/components/Projects.js
client/src/components/TdmCalculationContainer.js

- Fix badState warning when logging out due to adding /logout to react router; does not use setAccount in Route anymore; moved setAccount({}) to NavBarLogin with conditional check
- In Project.js - Made the styling for duplicate/delete modal overlay the same as the NavConfirmationModal
- Fix other linter, prettier warnings
- Delete unused variables/props
closes #595

Fix badState warning when logging out and fix other linter/prettier warnings

---

client/src/App.js
client/src/AppWrapper.js
client/src/hooks/useTracking.js
client/src/index.js

Add Google Analytics support

---

client/package-lock.json
client/package.json
docs/project-package-organization.md
lerna.json
package-lock.json
package.json
server/package-lock.json
server/package.json

Fixes #688 
This re-implements the git pre-commit hook that runs eslint on both client and server when a dev attempts to commit a change to their local repo.
Also added the `project-package-organization.md` readme, which attempts to explain how this works and how it should be used, with an emphasis on how to run different types of CLI commands in the proper folder.

Git commit hook

---

client/src/components/PrivacyPolicy.js
client/src/components/TermsAndConditions.js

Updated Privacy Policy on /Privacypolicy Page #691

691 update privacy policy

---

client/src/components/PublicComment/PublicCommentPage.test.js
client/src/components/PublicComment/postPublicComment.test.js
docs/development.md
server/app/controllers/email.controller.js
server/app/routes/email.routes.js
server/app/routes/index.js
server/app/services/sendgrid-service.js

Fix eslint errors

---

client/package-lock.json
client/package.json
client/src/App.js
client/src/AppInsights.js
client/src/components/TdmCalculationContainer.js
client/src/contexts/Toast/Toast.js
server/package-lock.json
server/package.json
server/server.js

Application insights

---

client/src/components/TermsAndConditions.js

Updated Terms and conditions text to add a hyperlink #697

updated terms and conditions with new link

---

client/src/App.js
client/src/AppWrapper.js
client/src/components/ProjectWizard/TdmCalculationWizard.js
client/src/components/Sidebar.js
client/src/components/TdmCalculationContainer.js
client/src/contexts/Toast/Toast.js
client/src/contexts/Toast/withToastProvider.js

Set the toast's createPortal target to the TDM Wizard/Main container components through the use of refs, automatically centering the toasts to these components. This means the Toast is now centered to these targets rather than the document.body.

470 sidebar ref solution

---

client/src/App.js
client/src/AppInsights.js
client/src/AppWrapper.js
client/src/components/About.js
client/src/components/Authorization/Login.js
client/src/components/ErrorPage.js
client/src/components/Projects/ProjectsPage.js
client/src/components/PublicComment/PublicCommentPage.js
client/src/components/Roles.js
client/src/components/TdmCalculationContainer.js
docs/application-insights.md

Tweaks to Application Insights

---

client/src/components/TermsAndConditionsModal.js

Updated Terms and conditions text to add a hyperlink #697

Updated popup Terms and Conditions

---

client/src/components/ProjectWizard/SidebarPoints/SidebarPoints.js
client/src/styles/theme.js

Refactored ticket based on Claire's comments.

713 change color of points

---

client/package-lock.json
client/package.json
server/db/migration/V20210217.1924__change_encouragement_program_tooltip_731.sql
server/package-lock.json

Change made to migration file, fixes #731.
Changes made to package.json to fix linter as well.

#731 Change Encouragement Tooltip

---

server/db/migration/V20210226.1844__update_school_level_calc.sql

Added migration to change school level calculation

---

client/package.json
client/src/services/tdm-engine.js
server/package.json

607 user defined strategy detail required

---

client/src/services/tdm-engine.js

Add validation for comment

---

client/src/components/ProjectWizard/WizardSidebar/EarnedPointsMetContainer.js

Success notification text edit #714

714 success notification target points earned points

---

client/src/components/About.js

About page contents changed. Subheader CSS borrowed from the TDM Wizard page to maintain consistency.

 Updated About page

---

server/db/migration/V20210331.1719__update_dropdown_choices_to_use_na_779.sql

Add migration file
closes #779

Update Affordable Housing Level and Shared Parking dropdown choices to use N/A

---

client/src/App.js
client/src/components/Authorization/Register.js
client/src/components/ProjectWizard/RuleCalculation/RuleCalculation.js
client/src/components/ProjectWizard/RuleInput/RuleInput.js
client/src/components/ProjectWizard/RuleStrategy/RuleStrategy.js
client/src/components/ProjectWizard/TdmCalculationWizard.js

Part of #740 Refactor Miscellaneous. Does not close.
Reasoning why I updated react router implementation:
"The recommended method of rendering something with a is to use children elements" (instead of render or component). From React Router documentation. Using component prop..." would create a new component every render. This results in the existing component unmounting and the new component mounting instead of just updating the existing component. "

Fix console warnings and update routes to use recommended react router implementation

---

client/src/components/About.js
client/src/components/Authorization/Login.js
client/src/components/Authorization/Register.js
client/src/components/Authorization/SendEmailForm.js
client/src/components/PrivacyPolicy.js
client/src/components/ProjectWizard/RuleInput/RuleInputLabel.js
client/src/components/ProjectWizard/RuleStrategy/RuleStrategyLabel.js
client/src/components/Projects/ProjectsPage.js
client/src/components/TermsAndConditions/TermsAndConditionsContent.js
client/src/styles/App.scss

Made link styling consistent throughout app #718. Added global styling for all "a" tags. Kept custom styling for specific "a" tags.

Made link styling consistent throughout app #718

---

client/src/components/About.js

closes #715  - Update About Page Copy
Subheaders are now left aligned.

715 update about

---

client/src/components/ProjectWizard/WizardPages/ProjectDescriptions.js

Subheader in calculation/1 changed. #794

794 Subheader Changed

---

client/src/components/NavBar.test.js
cypress/cypress/integration/project-calculations-no-auths/beatrice-building.spec.js
cypress/cypress/integration/project-calculations-no-auths/clarendon-apartments.spec.js
cypress/cypress/integration/project-calculations-no-auths/fountain-apartments.spec.js
cypress/cypress/integration/project-calculations-no-auths/jewish-family-service.spec.js
cypress/cypress/integration/project-calculations-no-auths/victory-hotel.spec.js
cypress/cypress/integration/project-crud-with-auths/project-crud-with-auths.spec.js
cypress/cypress/support/commands.js
cypress/package-lock.json

Closes #798 
Fixed broken navbar test
Fixed broken cypress tests, including making sure that earned points equal target points or more

798 Fix frontend and cypress tests

---

server/db/migration/V20210421.1652__update_bike_parking_spelling_803.sql

Update bike parking required spelling #803

---

client/src/components/ProjectWizard/RuleCalculation/RuleCalculation.js
client/src/components/ProjectWizard/WizardPages/ProjectSummary.js
server/db/migration/V20210414.1954__changed_spcs_to_spaces.sql

Closes #800 
All instances of spcs changes to Spaces in calculation page. Text in project summary center aligned.

800 Changes spc to Spaces

---

client/src/components/ProjectWizard/TdmCalculationWizard.js

Scroll window to top when navigating among Wizard pages

---

server/db/migration/V20210423.2115__update_car_share_strategy_791.sql
server/package-lock.json
server/package.json

Update Car Share Strategy 791

---

client/src/components/ProjectWizard/WizardPages/ProjectSummary.js

spcs changed to Spaces in summary. Horizontal align in 3rd page changed.

---

client/src/components/ProjectWizard/Common/Panels.js
client/src/components/ProjectWizard/RuleCalculation/RuleCalculationPanels.js
client/src/components/ProjectWizard/RuleInput/ParkingProvidedRuleInput.js
client/src/components/ProjectWizard/RuleInput/RuleInputPanels.js
client/src/components/ProjectWizard/TdmCalculationWizard.js
client/src/components/ProjectWizard/WizardPages/ProjectTargetPoints.js
client/src/components/ProjectWizard/helpers.js

Closes #801 
Making parking provided required
I also made a refactor of the RulesInputPanels and RuleCalculationPanels to use the same Panel component

801 parking provided required

---

client/package-lock.json
client/src/components/ProjectWizard/RuleInput/ParkingProvidedRuleInput.js
package-lock.json
server/db/migration/V20210501.0939__make_park_spaces_required.sql
server/package-lock.json

Migration for PR #818

---

server/db/migration/V20210526.1316__adjust_strategy_points_826.sql
server/db/migration/V20210526.1439__adjust_tooltips_827_832.sql
server/db/migration/V20210526.1442__adjust_applicable_land_uses_828_829.sql

Fixes #826, Fixes #827, Fixes #828, Fixes #829, Fixes #832

Issues 826, 827, 828, 829, 832

---

cypress/cypress/integration/project-calculations-no-auths/beatrice-building.spec.js
cypress/cypress/integration/project-calculations-no-auths/victory-hotel.spec.js
server/db/migration/V20210602.1741__update_range_choices_for_dropdowns.sql

Closes #839 
Please migrate against dev/prod DBs

Update dropdown choices to display full percentage range #839

---

client/src/components/ProjectWizard/RuleInput/RuleInputLabel.js
cypress/cypress/integration/project-calculations-no-auths/beatrice-building.spec.js
cypress/cypress/integration/project-calculations-no-auths/victory-hotel.spec.js
server/db/migration/V20210602.1741__update_range_choices_for_dropdowns.sql
server/db/migration/V20210602.1806__rename_ain_apn.sql

Closes #837 
Please merge the other PR first then this one.

837 ain apn number

---

server/db/migration/V20210602.1956__undo_issue_829.sql
server/package-lock.json
server/package.json
server/server.js

Fixes #829 by undoing it pending further review by LADOT

Undo Issue 829

---

client/src/components/ProjectWizard/RuleInput/ParkingProvidedRuleInput.js
client/src/components/TdmCalculationContainer.js

Auto-select EV Bonus when user selects BlueLA Car Share Membership

---

client/src/components/ProjectWizard/RuleInput/RuleInputLabel.js
client/src/components/ToolTip/ToolTipLabel.js

- Revised conditional showing tooltip icons within ToolTipLabel.js
- Based conditional on props - code instead of props- children

836 add habitibal rooms

---

server/db/migration/V20210709.2215__update_project_level_hotels_motels_855.sql

Update project level rule for hotel motel guest rooms #855

---

client/package-lock.json
client/package.json
client/src/components/ProjectWizard/CalculationWizardRoutes.js
client/src/components/ProjectWizard/RuleStrategy/RuleStrategyLabel.js
client/src/components/ProjectWizard/WizardPages/ProjectPackages.js
client/src/components/ToolTip/ToolTipLabel.js
cypress/package-lock.json
cypress/package.json
package-lock.json
package.json
server/package-lock.json
server/package.json

861 fix bug skips page4

---

server/db/migration/V20210722.1337__update_sqft_number_of_alternative_881_876_869.sql

Added DB migration file to do the following:
Remove Sq Ft from page 2
Closes #881 
Change # to Number of in page 2
Closes #876 
Change Version # to Alternative # 
Closes #869 
Add  #tooltip to Alternative #
Closes #887

881 876 869 rules sqft number of alternative

---

client/src/components/Projects/DuplicateProjectModal.js
client/src/components/Projects/ProjectsPage.js
cypress/cypress/integration/project-crud-with-auths/duplicate-project.js

Fix #859 . 
I also added a cypress test so that this will get caught earlier next time.

859 duplicate project bug

---

server/db/migration/V20210805.2119__update_child_care_display_858.sql
server/db/migration/V20210806.1746__update_school_safety_strategy_858.sql

- Allowed Child Care strategy with all projects, except for housing
- Excluded School Safety Campaign strategy from Employment, Retail, and Housing uses 
#858

updated child care display rules and school safety campaign strategy #858

---

client/src/components/ProjectWizard/RuleInput/RuleInput.js

Hide disabled subinputs on specifications page

---

client/src/components/ProjectWizard/WizardSidebar/EarnedPointsProgress.js
client/src/components/ProjectWizard/WizardSidebar/SidebarCart.js
client/src/styles/Calculation.scss

Issue #908 partial cleanup, pending further suggestions from UI/UX team

Minor cleanup of Earned Points Progress Controls and Cart

---

client/src/components/Button/SaveButton.js
client/src/components/ProjectWizard/TdmCalculationWizard.js
client/src/components/ProjectWizard/WizardFooter.js
cypress/cypress/integration/project-crud-with-auths/project-crud-with-auths.spec.js
cypress/cypress/integration/save-button.spec.js

This should close #777
screenshot showing hidden save button for guest user.

777 hide save for guest users

---

client/src/components/ProjectWizard/WizardSidebar/SidebarPoints.js
client/src/components/ProjectWizard/WizardSidebar/SidebarPointsPanel.js
client/src/components/ProjectWizard/WizardSidebar/WizardSidebar.js
client/src/styles/Calculation.scss

Go back to Earned/Target Point numbers on sidebar

---

client/src/components/ProjectWizard/WizardSidebar/SidebarPointsPanel.js

Temporarily include the Earned Points Progress Meter for A/B testing it's usability with users.

Switch on the Earned Points Progress Meter

---

client/src/components/ProjectWizard/WizardSidebar/EarnedPointsProgress.js
client/src/components/ProjectWizard/WizardSidebar/SidebarPointsPanel.js

922 earned points control test

---

client/public/index.html
client/src/components/ProjectWizard/CalculationWizardRoutes.js
client/src/components/ProjectWizard/WizardPages/ProjectSummary.js
client/src/components/ProjectWizard/WizardPages/ProjectSummary/LandUses.jsx
client/src/components/ProjectWizard/WizardPages/ProjectSummary/MeasureSelected.jsx
client/src/components/ProjectWizard/WizardPages/ProjectSummary/PointsEarnedMessage.jsx
client/src/components/ProjectWizard/WizardPages/ProjectSummary/ProjectDetail.jsx
client/src/components/ProjectWizard/WizardPages/ProjectSummary/ProjectInfo.jsx
client/src/components/ProjectWizard/WizardPages/ProjectSummary/ProjectInfoContainer.jsx
client/src/components/ProjectWizard/WizardPages/ProjectSummary/ProjectSummary.js
client/src/components/ProjectWizard/WizardPages/ProjectSummary/Result.jsx
client/src/components/ProjectWizard/WizardPages/ProjectSummary/index.js
client/src/components/ProjectWizard/WizardSidebar/EarnedPointsProgress.js
client/src/components/ProjectWizard/helpers.js
cypress/cypress/integration/project-calculations-no-auths/barrington-condos.spec.js
cypress/cypress/integration/project-calculations-no-auths/residental.spec.js

Summary page rearrange display elements
Screenshots
Closes #913

913 update summary page

---

client/src/components/PublicComment/postPublicComment.js
client/src/components/PublicComment/postPublicComment.test.js

Fix breaking tests for postPublicComment

---

client/src/components/Sidebar.js

Make sidebar background use same scaling wherever it is used

---

client/src/components/ToolTip/ToolTipIcon.js

#956
Changed all tooltip question mark colors from white to blue.

All instances of the tooltip made blue

---

Dockerfile
client/src/components/Authorization/Login.js
client/src/components/PublicComment/postPublicComment.test.js

Fixing a lint error in client code, but also modified Dockerfile to use the lts-alpine version of node for building the container.

Modify Dockerfile to build container w/ LTS version of node

---

client/src/components/ProjectWizard/WizardPages/ProjectSummary/PointsEarnedMessage.jsx
client/src/components/ProjectWizard/WizardPages/ProjectSummary/ProjectDetail.jsx
client/src/components/ProjectWizard/WizardPages/ProjectSummary/ProjectInfo.jsx
client/src/components/ProjectWizard/WizardPages/ProjectSummary/ProjectInfoContainer.jsx
client/src/components/ProjectWizard/WizardPages/ProjectSummary/ProjectSummary.js
client/src/components/ProjectWizard/WizardPages/ProjectSummary/Result.jsx
server/db/migration/V20211028.1600__update_parking_baseline_rule_name_970.sql

970 update summary page

---

client/src/components/ProjectWizard/WizardPages/ProjectSummary/ProjectSummary.js

Fix bug when initial project desription is null

---

client/src/components/ProjectWizard/CalculationWizardRoutes.js
client/src/components/ProjectWizard/TdmCalculationWizard.js
client/src/components/ProjectWizard/WizardPages/ProjectMeasures.js
client/src/components/ProjectWizard/WizardPages/ProjectPackages.js
client/src/components/TdmCalculationContainer.js
server/db/create-migration
server/db/migration/V20211117.1246__revise _packages_998.sql

Re-organize packages

---

client/src/components/ProjectWizard/WizardPages/ProjectSummary/PointsEarnedMessage.jsx
client/src/components/ProjectWizard/WizardPages/ProjectSummary/ProjectInfo.jsx
client/src/components/ProjectWizard/WizardPages/ProjectSummary/ProjectInfoContainer.jsx
client/src/components/ProjectWizard/WizardPages/ProjectSummary/ProjectSummary.js

The rest of the summary page updates.
Closes #970

970 2 updated summary page

---

server/db/migration/V20211203.1958__make-telecommute_strategies_independent_618.sql

Make telecommute strategies independent

---

server/db/migration/V20211203.2030__mutually_exclusive_parking-strategies_999.sql

Mutually exclusive parking strategies

---

server/db/migration/V20211203.2100__consolidate_bike_share_strategies_1007.sql

Consolidate bike share strategies

---

server/db/migration/V20211207.1533__page_2_language_edits_1009.sql

Project Specifications Language & Rule changes

---

client/src/components/ProjectWizard/RuleCalculation/RuleCalculation.js
client/src/components/ProjectWizard/RuleInput/ParkingProvidedRuleInput.js
client/src/components/ProjectWizard/WizardPages/ProjectTargetPoints.js
client/src/components/TdmCalculationContainer.js

964 allow 0 provided parking

---

client/src/components/ProjectSinglePage/RuleList.js
client/src/components/ProjectWizard/RuleCalculation/RuleCalculationList.js
client/src/components/ProjectWizard/RuleInput/RuleInputList.js
server/db/migration/V20211207.1817__allow_0_provided_parking_964.sql

Remove refences to calculationRule.id values

---

client/src/components/ProjectWizard/WizardPages/ProjectPackages.js
cypress/package-lock.json

Edit Package Page working

---

server/db/migration/V20211222.1946__fix_televisits_points_618.sql

Fix points for televisits

---

server/db/migration/V20211222.2003__minor_strategy_name_changes_1030.sql

Minor name changes to specification inputs

---

server/db/migration/V20211222.2039__high_school_specification_name_change_1030.sql

Fix to Issue #1030

---

client/src/components/Authorization/Login.js
client/src/components/Authorization/Register.js
client/src/components/Authorization/ResetPassword.js
client/src/components/Authorization/SendEmailForm.js
client/src/components/ProjectWizard/RuleInput/ParkingProvidedRuleInput.js
client/src/components/ProjectWizard/RuleInput/RuleInput.js
client/src/components/ProjectWizard/RuleInput/RuleInputList.js
client/src/components/ProjectWizard/RuleInput/RuleInputPanels.js
client/src/components/ProjectWizard/RuleStrategy/RuleStrategy.js
client/src/components/ProjectWizard/RuleStrategy/RuleStrategyList.js
client/src/components/ProjectWizard/RuleStrategy/RuleStrategyPanels.js
client/src/components/PublicComment/PublicCommentPage.js

Implement auto-focus on first field fo forms

---

client/src/components/ProjectWizard/WizardPages/ProjectSummary/ProjectSummary.js
client/src/components/ProjectWizard/WizardSidebar/SidebarCart.js

Relabeled 'TDM MEASURES SELECTED' to 'TDM STRATEGIES SELECTED' 
Closes #1050

1050 relabel tdm measures selected

---

client/src/App.js
client/src/AppWrapper.js
client/src/components/Admin.js
client/src/components/Authorization/Login.js
client/src/components/Authorization/Unauthorized.js
client/src/components/Header.js
client/src/components/NavBar.js
client/src/components/NavBarLogin.js
client/src/components/ProjectSinglePage/RuleFunction.js
client/src/components/user-context.js
client/src/contexts/UserContext.js

Fixes #1033
As part of this, create UserContext to keep the logged-in user information in a react context, vs passing props.

1033 apply client routing auth

---

client/src/components/ToolTip/AccordionToolTip.js

Updated accordion description widths to be compatible with Safari and Firefox browsers.

1036 accordion design tooltips

---

server/db/migration/V20220207.1702__move-help-links-inside-tooltips_1058.sql

Move help links inside accordion tooltips

---

server/db/migration/V20220207.1702__move-help-links-inside-tooltips_1058.sql

1058 move help links inside tooltips

---

server/db/migration/V20220212.0932__fix_spelling_in_toolltip_1058.sql

Fix spelling error in AIN tooltip

---

client/package.json
client/src/components/ProjectWizard/RuleInput/MultiInput.jsx
client/src/components/ProjectWizard/RuleInput/RuleInput.js
client/src/components/TdmCalculationContainer.js
cypress/cypress/integration/project-calculations-no-auths/all-strategies.spec.js
cypress/cypress/integration/project-calculations-no-auths/barrington-condos.spec.js
cypress/cypress/integration/project-calculations-no-auths/employment-office.spec.js
cypress/cypress/integration/project-calculations-no-auths/hotel.spec.js
cypress/cypress/integration/project-calculations-no-auths/medical-care.spec.js
cypress/cypress/integration/project-calculations-no-auths/residental-with-residental-package.spec.js
cypress/cypress/integration/project-calculations-no-auths/retail.spec.js
cypress/cypress/integration/project-calculations-no-auths/schools-with-employment-package.spec.js
cypress/cypress/integration/project-calculations-no-auths/special-uses.spec.js
cypress/cypress/integration/project-calculations-no-auths/warehouse.spec.js
cypress/cypress/integration/project-crud-with-auths/project-crud-with-auths.spec.js
cypress/cypress/integration/project-reset.spec.js
cypress/cypress/integration/save-button.spec.js

- Use React Select to provide tag functionality
- Use input mask inside to force the AIN input format
- Create new AIN tag when user presses tab, comma, or enter, or if any key is pressed after all the AIN digits are present
- AIN tag displays in red if the tag is invalid, and the box takes on a solid red outline with an error message
- Don't allow empty tag or duplicate value tags
- Set placeholder text to add another AIN when there's already one present
- Validate AIN tags on page load
Closes #1010

1010 multiple AIN tags

---

client/src/App.js
client/src/components/ProjectWizard/TdmCalculationWizard.js
cypress/cypress/integration/navigation-and-pages.spec.js
cypress/cypress/integration/user-auths/login.spec.js

Terms and Conditions modal now shows up on any page. Once dismissed, it will not show again for any page.
Closes #1082

Move terms and conditions modal to all pages

---

client/src/components/ProjectWizard/WizardPages/ProjectMeasures.js

Remove subheader and ? icon from strategy page

---

client/src/components/ProjectWizard/CalculationWizardRoutes.js
client/src/components/ProjectWizard/PackagePanel/PackagePanel.js
client/src/components/ProjectWizard/PackagePanel/PackageToolTip.js
client/src/components/ProjectWizard/PackagePanel/PackageTooltips.js
client/src/components/ProjectWizard/PackagePanel/PanelHeader.js
client/src/components/ProjectWizard/PackagePanel/RulePackage.js
client/src/components/ProjectWizard/RuleStrategy/RuleStrategy.js
client/src/components/ProjectWizard/TdmCalculationWizard.js
client/src/components/ProjectWizard/WizardPages/ProjectMeasures.js
client/src/components/TdmCalculationContainer.js
server/db/flyway-config.js

Bonus package info moved to accordions

---

client/package-lock.json
client/src/components/ProjectWizard/PackagePanel/PackagePanel.js
client/src/components/ProjectWizard/PackagePanel/RulePackage.js
client/src/components/ProjectWizard/WizardPages/ProjectMeasures.js
client/src/components/TdmCalculationContainer.js

1071 bonus package UI

---

client/src/components/ProjectWizard/PackagePanel/PackageTooltips.js

Minor adj to vertical spacing of package tooltip table

---

client/package-lock.json
client/src/App.js
client/src/AppWrapper.js
client/src/components/Checklist/ChecklistContent.js
client/src/components/Checklist/ChecklistModal.js
client/src/components/Footer.js
client/src/components/ProjectWizard/TdmCalculationWizard.js
client/src/components/TdmCalculationContainer.js
cypress/cypress/support/commands.js
package-lock.json
server/package-lock.json

Closes #1086 
Finalized checklist modal

1086 checklist popup

---

client/src/components/ProjectWizard/RuleInput/MultiInput.jsx
client/src/components/ProjectWizard/RuleInput/RuleInput.js

Progress on #1010
- put AIN values above the input
- fixed input field highlight
- Add spacing between AIN tags
- persist AIN input field error when focusing away
- auto create AIN tag when input loses focus if input value is valid

1010 multiple ain fix

---

server/db/migration/V20220325.0859__strategy_changes_1097.sql

Strategy Changes

---

server/db/migration/V20220325.0923__threshold_changes_1096.sql

Threshold Changes per issue 1068

---

.vscode/settings.json
server/db/migration/V20220402.1008__modify_stadium_level_2_threshold.sql

Modified Level 2 Threshold for stadiums w/o seats

---

client/src/components/ProjectWizard/CalculationWizardRoutes.js
client/src/components/ProjectWizard/RuleInput/MultiInput.jsx
client/src/components/ProjectWizard/RuleInput/RuleInput.js
client/src/components/ProjectWizard/RuleInput/RuleInputList.js
client/src/components/ProjectWizard/RuleInput/RuleInputPanels.js
client/src/components/ProjectWizard/TdmCalculationWizard.js
client/src/components/ProjectWizard/WizardPages/ProjectDescriptions.js

Part of #1010 
- Disable next navigation when there's an AIN error
- Empty input is not an invalid AIN

1010 multiple ain fix2

---

server/db/migration/V20220412.0912__modify_access_improvement_strategy_1116.sql

1116 access improvements startegy changes

---

client/src/components/ProjectWizard/WizardPages/ProjectSummary/ProjectInfo.jsx
client/src/components/ProjectWizard/WizardPages/ProjectSummary/ProjectInfoContainer.jsx
client/src/components/ProjectWizard/WizardPages/ProjectSummary/ProjectInfoList.jsx

Remove the DropDown and Update final summary page AIN's no. in a row.

Working 1024 issue

---

server/db/migration/V20220513.1136__update_tooltips.sql

DB Migration to update tooltips for Issue #1152

---

server/db/migration/V20220513.1240__hotel_enable_unbundling_856.sql

Enable Parking Unbundling Strategy for Hotels

---

client/src/components/TdmCalculationContainer.js

Closes #907 fixed last saved timestamp

907-fix-last-saved-timestamp

---

server/db/migration/V20220527.2139__modify_wording_of_reduced_parking_tooltip_1162.sql

Remove ref to Glossary from Reduced Parking tooltip

---

.vscode/settings.json
client/src/components/ProjectWizard/CalculationWizardRoutes.js
client/src/components/ProjectWizard/RuleInput/ParkingProvidedRuleInput.js
client/src/components/ProjectWizard/RuleInput/RuleInput.js
client/src/components/ProjectWizard/RuleInput/RuleInputList.js
client/src/components/ProjectWizard/RuleInput/RuleInputPanels.js
client/src/components/ProjectWizard/RuleStrategy/RuleStrategy.js
client/src/components/ProjectWizard/TdmCalculationWizard.js
client/src/components/ProjectWizard/WizardPages/ProjectTargetPoints.js
client/src/components/ProjectWizard/WizardSidebar/SidebarCart.js
client/src/components/ProjectWizard/WizardSidebar/SidebarPointsPanel.js
client/src/components/ProjectWizard/WizardSidebar/WizardSidebar.js
client/src/components/TdmCalculationContainer.js
client/src/index.js
server/db/migration/V20220602.1517__add_readonly_field_to_calculation_rule_1164_1149.sql

1164 reduced parking mods

---

client/src/components/TdmCalculationContainer.js

Fixes minor bug in Issue #1164 implementation.

Fix bug in 1164

---

client/src/components/ProjectWizard/PackagePanel/RulePackage.js
client/src/components/ProjectWizard/RuleStrategy/RuleStrategy.js
client/src/components/ToolTip/AccordionToolTip.js
client/src/components/ToolTip/ToolTipLabel.js

Closes #1172 updated opacity of rulestrategy and tooltip description

1172 updated opacity of rulestrategy and tooltip description

---

server/db/migration/V20220604.0941__update_encouragement_program_tooltip_1124.sql

Modify Encouragement Program Tooltip

---

server/db/migration/V20220605.1506__change_reduced_parking_tooltips_1186.sql

Modified tooltips for Reduced Parking per Issue 1186

---

server/db/migration/V20220605.1624__change_alternate_number_tooltip_1185.sql

Change tooltip for Alternative # Input

---

client/src/components/ProjectWizard/WizardPages/ProjectMeasures.js
client/src/components/ProjectWizard/WizardPages/ProjectSpecifications.js
client/src/components/ProjectWizard/WizardPages/ProjectTargetPoints.js

Update Wiard page 2,3,4 Headings

---

client/src/components/ProjectWizard/WizardPages/ProjectDescriptions.js

Change Heading on page 1 of Wizard

---

server/db/migration/V20220704.1546__modify_project_address_tooltip_1141.sql

Change tooltips for AIN and Address

---

client/src/components/About.js
client/src/components/ProjectWizard/WizardPages/Level0Page.jsx

Change Text on Target Points Page for Level 0 projects

---

client/src/components/ProjectWizard/PackagePanel/PackageTooltips.js

Change Bonus Package Tooltips Again

---

client/src/components/Checklist/ChecklistContent.js

Change wording of checklist footnote

---

client/src/components/ProjectWizard/WizardPages/ProjectSpecifications.js
server/db/migration/V20220706.1306__fix_to_1141.sql

1141 change tooltips for ain and address

---

client/package-lock.json
server/db/migration/V20220706.1325__change_residential_specifcations_ui_1209.sql

1209 rearrange residential specs

---

client/src/components/ProjectWizard/WizardSidebar/SidebarCart.js
server/db/migration/V20220706.1351__change_tooltips_for_reduced_parking_1206.sql

Make changes to Reduced Parking -related tooltips and cart message

---

client/package-lock.json
client/src/components/About.js
package-lock.json
server/package-lock.json

Updated link for Proposed Ordinances and Initiatives 
Closes #865

Updated link for Proposed Ordinances and Initiatives #865

---

package-lock.json
server/db/migration/V20220719.1939__update_shared_parking_tooltip.sql
server/package-lock.json

Closes #1168 update shared parking tooltip description

1168 update shared parking tooltip description

---

server/db/migration/V20220719.1956__update_encouragement_program_tooltip_3.sql

Closes #1124 update encouragement program tooltip 3

1124 update encouragement program tooltip 3

---

client/src/components/ProjectWizard/RuleInput/MultiInput.jsx
client/src/components/ProjectWizard/RuleInput/RuleInput.js
client/src/components/ProjectWizard/RuleInput/RuleInputList.js
client/src/components/ProjectWizard/RuleInput/RuleInputPanels.js
client/src/components/ProjectWizard/WizardPages/ProjectDescriptions.js
client/src/components/PublicComment/PublicCommentPage.js

Added required / optional placeholders to inputs on Page 1

---

client/package-lock.json
client/src/App.js
client/src/components/Checklist/ChecklistModal.css
client/src/components/Checklist/ChecklistModal.js
package-lock.json
server/package-lock.json

Closes #1157 Updated scope of Checklist modal and added transition styling.

fixed checklist modal scope and added transition

---

server/db/migration/V20220803.1517__modify_description_tooltip_1158.sql

Update Project Description Tooltip

---

client/src/components/ProjectWizard/RuleInput/RuleInputPanels.js
client/src/components/ProjectWizard/WizardPages/DiscoverTooltips.js
client/src/components/ProjectWizard/WizardPages/ProjectDescriptions.js
client/src/components/ToolTip/ToolTipLabel.js

Closes #1223 
Created new component, DiscoverTooltips, and inserted it within ProjectDescriptions

1223 discoverability tooltips

---

server/db/migration/V20220810.1525__change_page-1-tooltips_1226.sql

Modify Page 1 tooltips

---

client/src/components/ProjectWizard/WizardSidebar/EarnedPointsProgress.js

Make target points circle and number bigger on sidebar

---

server/db/migration/V20221014.1955__fix_spelling_in_sidebar_tooltip1245.sql

Fix sidebar tooltip spelling

---

server/db/migration/V20221014.2002__project_description_remove-asterisk_1246.sql

1249 project description remove asterisk

---

client/src/components/NavBar.js
client/src/components/PublicComment/PublicCommentPage.js

Changed Public Comment Form to Feedback Form

---

server/server.js

Fix application insights

---

client/src/components/FaqCategory/FaqCategory.js
client/src/services/faqCategory.service.js
server/app/controllers/faqCategory.controller.js
server/app/routes/faqCategory.routes.js
server/app/services/faqCategory.service.js
server/db/migration/V20221113.1303__add_faq_category_table.sql

Added DB migration for the faqCategory table and started creating server side files in order to retrieve faqCategory on the client side.

Added DB migration for the faqCategory table, server side files

---

server/db/migration/V20220803.1517__modify_description_tooltip_1158 2.sql
server/db/migration/V20221120.0951__edit_this_description_after_the_two_underscores.sql

Fixed design issues with Faq table, created standard CRUD stored procedures for Faq and FaqCategory tables.

Added stored procedures for Faq, FaqCategory

---

client/src/services/faq.service.js
client/src/services/faqCategory.service.js
server/db/migration/V20221123.1759__add_applicability_explanations_to_strtaegy-tooltips_1276.sql

Add applicability information to strategy tooltips where it applies

---

server/db/migration/V20221123.1926__fix_to_issue_1276.sql

Fix to tooltip for televisit strategy

---

client/src/components/Faq/Faq.js
server/db/migration/V20221127.2030__populate_initial_faqs_1280.sql

Populate FAQ with initial questions

---

client/src/App.js
client/src/components/Faq/FaqView.js
server/db/migration/V20221201.1517__populate_initional_faqs_take2_1280.sql

Update to initial FAQs

---

client/src/services/tdm-engine.js

1284 auto deselect inapplicable strategies

---

server/db/migration/V20221202.1117__modify_hotel_level_thresholds_1287.sql

Modify Hotel Level Thresholds

---

Dockerfile
client/src/components/About.js
client/src/components/Footer.js

Add glossary links to footer and about page

---

client/src/components/ProjectWizard/WizardPages/ProjectMeasures.js

Make sure Package Bonus section is completely hidden if not applicable

---

server/db/migration/V20230111.1526__more_mods_to-_greyed_toolitps_1244.sql

More changes to Greyed Out Tooltips for strategy applicability

---

server/db/migration/V20230121.1505__populate_initional_faqs_take3_1280.sql

Minor fixes to FAQ content

---

client/package-lock.json
client/src/App.js
client/src/components/InapplicableStrategiesModal.js
client/src/components/ProjectWizard/TdmCalculationWizard.js
client/src/components/TdmCalculationContainer.js
client/src/styles/theme.js
package-lock.json
server/package-lock.json

Closes #1285 
Completed Implement a Notification that Strategies Have Been Automatically De-Selected

1285 notification strategies deselected

---

Dockerfile

First attempt to fix deployment to Azure

---

client/src/components/PrivacyPolicy.js

Closes #1239
Updated Privacy Policy page links

1239 update privacy links

---

client/src/AppWrapper.js

Closes #1332 
Fixed checklist rendered after dismissed

1332 checklist rendered after dismissed

---

client/src/components/ProjectWizard/WizardPages/ProjectSummary/ProjectSummary.js

#1329 
Fixed typography changes

1329 changes to summary page

---

client/src/styles/theme.js

Add new system design items to Theme.JS..This work does not update the UI components. 
In addition, I left the current colors in place as to not cause unwanted side-affects. Once these references have been replaced with colors from the theme, we can delete this code.

Add system design updates to Theme JS

---

client/src/components/Authorization/Login.js
client/src/components/Button/Button.js
client/src/styles/theme.js

[1346 - Integrate System Design - Login](https://github.com/hackforla/tdm-calculator/issues/1346)
- Add new theme typography to Login headers + error handling.
- Additional work to set the Login button to disable if error/no value in Login Form.

1346 login theme

---

server/app/schemas/account.role.js

Fix bug in granting/revoking roles

---

Dockerfile

Attempt to fix Dockerfile bug

---

client/src/components/Roles.js
server/app/routes/account.routes.js
server/app/routes/calculation.routes.js
server/app/routes/faq.routes.js
server/app/routes/faqCategory.routes.js
server/app/routes/rule.routes.js
server/middleware/jwt-session.js

Fix to Privilege Escalation Attack

---

client/src/components/Button/Button.js
client/src/components/Projects/ProjectsPage.js
client/src/components/Roles.js
client/src/services/account.service.js
server/middleware/jwt-session.js

Improve response to 401/403 on roles page

---

client/src/components/Authorization/Login.js
server/app/services/sendgrid-service.js

Change links in Feedback Form email to take user to login page

---

client/package-lock.json
client/src/components/Button/DownloadButton.js
client/src/components/Button/PrintButton.js
client/src/components/PdfPrint/PdfPrint.js
client/src/components/ProjectWizard/TdmCalculationWizard.js
client/src/components/ProjectWizard/WizardFooter.js
client/src/components/Projects/ProjectsPage.js
client/src/components/PublicComment/PublicCommentPage.test.js
package-lock.json
server/app/schemas/account.register.js
server/app/schemas/account.updateAccount.js
server/package-lock.json

Changed the 'Download Summary' button to 'Print Summary' and changed the icon from a file download to a print icon.

Download button to print

---

client/package-lock.json

Fix for build error: https://github.com/hackforla/tdm-calculator/actions/runs/5886770205

fix build error by installing packages

---

.github/workflows/new-issue-create-card.yml

Attempt to fix 'Create Card for New Issues' github action

---

client/package-lock.json
client/package.json
client/src/components/Button/AddNewCategory.jsx
client/src/components/Button/Button.js
client/src/components/Button/EditToggleButton.js
client/src/components/Faq/Answer.jsx
client/src/components/Faq/CategoryInput.jsx
client/src/components/Faq/Faq.js
client/src/components/Faq/FaqButtonContainer.jsx
client/src/components/Faq/FaqCategory.js
client/src/components/Faq/Question.jsx

Fixes 2, 3, 4, and 6 of https://github.com/hackforla/tdm-calculator/issues/1305#issuecomment-1692080297. 
1, 5 is ccurrently in process

Styling and UI cleanup based on Design team comments

---

client/src/components/Button/Button.js
client/src/components/Faq/DeleteFaqModal.jsx
client/src/components/Faq/Faq.js
client/src/components/Faq/FaqCategory.js
client/src/components/Faq/FaqList.jsx
client/src/components/Faq/FaqView.jsx
client/src/components/Faq/Question.jsx
client/src/components/UI/AriaModal/ModalDialog.js

- Add "warning" styling for button component
- Add delete Category/FAQ dialog component 
- clean up of types
- Modification to dialog component so when a user is scrolled down, they can see the modal. @Jonathanko52 Can you please verify this works across other modal dialogs you have worked on?

Add delete modal for FAQ, types cleanup

---

client/package-lock.json
client/package.json
client/src/components/Projects/ProjectContextMenu.js
client/src/components/Projects/ProjectsPage.js
server/app/controllers/project.controller.js
server/app/routes/project.routes.js
server/app/services/project.service.js
server/db/migration/V20230906.2053__changes_to_support_hide_trash_snapshot.sql

Database and Web API parts of the following Issues:
- #1435 
- #1436 
- #1437

DB and Web API for hide, trash and snapshot

---

client/package-lock.json
client/src/components/Checklist/ChecklistContent.js

#1446 Spelling fixed in checklist modal

Spelling fixed

---

client/src/components/Faq/FaqView.jsx
client/src/components/Faq/SaveConfirmationModal.jsx

Add save confirmation modal in FAQ

---

client/src/components/Faq/Answer.jsx
client/src/components/Faq/DeleteFaqModal.jsx
client/src/components/Faq/FaqView.jsx
client/src/components/Faq/SaveConfirmationModal.jsx
client/src/components/Projects/DeleteProjectModal.js
client/src/components/UI/AriaModal/ModalDialog.js

FAQ Modal styling cleanup plus refactoring of the text editor logic so that tooltip clicks are recognized as part of the edit answer mode.

FAQ Dialog styling refactor

---

client/src/components/ProjectWizard/RuleInput/ParkingProvidedRuleInput.js
client/src/components/ProjectWizard/WizardPages/ProjectTargetPoints.js
server/db/migration/V20231003.1432__disable_strategies_when_no_parking_provided_1434.sql

Disable selected strategies when no parking provided 1434

---

client/src/App.js
client/src/components/Authorization/RequireAuth.js

Partial Fix for  #1487
upgrade code to follow best practices for react-router v5, prior to upgrading to v6.
To keep up to data with reacct-router version
(none)
(none)

Upgrade to react-router 5

---

client/src/components/Projects/ProjectContextMenu.js

Fixes #1435
Logic to switch between hide/unhide options on Context Menu was not right.

Fix logic of hide/unhide context menu on My Projects

---

client/src/components/Feedback/FeedbackPage.js
client/src/components/Projects/ProjectContextMenu.js
client/src/components/Projects/ProjectTableRow.js
client/src/components/Projects/ProjectsPage.js
client/src/hooks/useGetProjects.js

Fixes #1518 + #1516 together
* close menu explicitly by wrapping the action handlers
* refresh projects collection after making service calls

1518 + 1516 after context menu action, close menu and update project row

---

client/src/components/Checklist/ChecklistContent.js
client/src/hooks/useErrorHandler.js

Fixes #1539
Fixed formatting of checklist contents - as modal and separate page 
per Bonnie
(none)
(see Issue #1539)

Checklist content formatting

---

client/src/components/PdfPrint/PdfPrint.js
client/src/components/ProjectWizard/WizardFooter.js
client/src/components/Projects/ProjectContextMenu.js
client/src/components/Projects/ProjectTableRow.js
client/src/components/Projects/ProjectsPage.js

- Fixes #1541 
- Fixes #1542
See Issues for changes.
New My Projects Grid:
Old Print Dialog (Note presence of scrollbar on the report itself)
New Print Dialog (Note absence of scrollbar on the report itself)

Update MyProjects grid column headings and cell formats, Remove scrollbar from printed Calculation Summary

---

client/src/components/Checklist/ChecklistModal.js
package-lock.json
package.json

Fixes #1530 
- Re-implemented modal close animation by copying over previous code linked below.
- https://github.com/hackforla/tdm-calculator/pull/1237
- The animation feature was requested so the user would know where to find the checklist after it is closed.
securityadmin@dispostable.com account was used to test animation.
<details>
</details>
<details>
https://github.com/hackforla/tdm-calculator/assets/133067265/6a5fbad7-4058-48ad-afa8-e3105adbd142
</details>

re-implement the checklist modal close animation

---

server/db/migration/V20240104.1714__add_about_table_to_db_1531.sql
server/report.html
server/report.json

Creates the About table for Issue #1531.  
Iris will still need to do an additional database migration to add the needed stored procedures.

Add About table to db

---

client/src/components/Projects/ProjectContextMenu.js
client/src/components/Projects/ProjectTableRow.js
client/src/components/Projects/ProjectsPage.js
client/src/components/Projects/RenameSnapshotModal.js
client/src/services/project.service.js
server/app/controllers/project.controller.js
server/app/routes/project.routes.js
server/app/services/project.service.js

Fixes #1556
1.Set up client side put service
2. api endpoint.
3.Project_Rename stored procedure
4. Snapshot rename modal
5. Edited context modal to conditionally change between "convert to snapshot, rename snapshot, rename snapshot(disabled).
1. Allow users to rename snapshots they've created.
2. NOT-allow users to rename other peopler's snapshots.

1556 Rename Snapshot

---

client/src/App.js
client/src/components/Authorization/Logout.js
client/src/components/Layout/NavBarLogin.js
client/src/services/account.service.js
server/app/routes/account.routes.js

Created Logout File in client/src/components/Authorization/Logout.js, JWT Token - Clear cookie
Fixes #412 
- Created a logout route client/src/App.js
- Added a new file for logout functionality: client/src/components/Authorization/Logout.js
- Edited client/src/components/Layout/NavBarLogin.js - Changed pathname: /login/${(account && account.email) || ""} to pathname: /logout`,
- Added logout function in service file: client/src/services/account.service.js
- Modified logout function in server route: server/app/routes/account.routes.js to clear the JWT cookie.
- To resolve jwt token issue

Logout Functionality

---

client/src/components/ProjectWizard/WizardPages/ProjectDescriptions.js
client/src/components/ProjectWizard/WizardPages/ProjectSpecifications.js

Fixes #1600
- Converted one div element with the content "designates required fields" from SCSS to JSS format.
- Converted one span element with the asterisk from SCSS to JSS format.
- To consolidate CSS to fewer places to minimize styling issues.
The [securityadmin@dispostable.com](mailto:securityadmin@dispostable.com) account was used.
<details>
</details>
<details>
</details>

Converted SCSS to JSS in ProjectDescriptions.js

---

server/__tests__/faqCategory.test.js
server/app/controllers/faqCategory.controller.js
server/app/schemas/faqCategory.js

added faqCategory test case file in __test__ and added faqCategory validation schema
Fixes #1581 
- Added new file faqCategory.test.js to __test__ in server directory. 
- Added new file faqCategory.js in server/app/schemas/
- Changes made to file faqCategory.controller.js in server/app/controllers to implement validation for post request
- To implement test cases for the faqcategories api

faqCategory-Testcase-and-Validation

---

server/__tests__/email.test.js

Fixes #1554 
- adds tests for the email endpoint

email tests after linting

---

client/src/components/Projects/ProjectTableRow.js

Fixes #1604
- Reordered the CSV column done by Emily and Xander(LACP/LADOT) per Issue #1591
- The downloaded CSV file is in the Sheet2 tab [TDM EXAMPLE CSV](https://docs.google.com/spreadsheets/d/1fPj-RdfQjyTF7hSXwZpKB8KwhqQC2B4ZpjbjvznYbBw/edit?usp=sharing)
- The changes were made for better functionality of the CSV file.
[ladot@dispostable.com](mailto:ladot@dispostable.com) account was used to verify the CSV file download.
There are no visual changes.

Reordered CSV columns

---

client/src/components/Faq/DeleteFaqModal.jsx
client/src/components/Projects/DeleteProjectModal.js
client/src/components/Projects/MultiProjectToolbarMenu.js
client/src/components/Projects/ProjectContextMenu.js

Fixes #1661 
- Changed the trash icon for restore function with trash icon with an arrow up.
- Changed the old trash icon to match the shape of the restore trash icon.
- The icon for the restore from delete function needed to be changed to visually clarify the function of the button.
Account tdm@hackforla.org was used for testing.
<details>
</details>
<details>
</details>

changed trash icon and color for restore from delete

---

client/package-lock.json
client/src/components/ProjectWizard/TdmCalculationContainer.js
client/src/components/ProjectWizard/TdmCalculationWizard.js
client/src/components/ProjectWizard/WizardFooter.js
package-lock.json

Fixes #1674 
- Added the Snapshot created and last saved dates to page 5 of the create project page.
- So users can see when a project was snapshot and when it was last saved.
<details>
</details>
<details>
</details>

1674 - Added snapshot and last saved dates to tdm project calculator summary

---

client/src/components/PdfPrint/PdfPrint.js
client/src/components/PdfPrint/PdfResult.js
client/src/components/ProjectWizard/WizardPages/ProjectSummary/ProjectInfoList.jsx
client/src/components/ProjectWizard/WizardPages/ProjectSummary/ProjectSummary.js

Fixes #1568
- Points tab indent
- Text size increase
- Entire reformatting of the PDF view
- Was asked to make the aforementioned changes 
Mike Odnis
~~If you registered a new, temporary TDM User Account for this issue, indicate the
username (i.e., email address) for the account.~~
<details>
</details>
<details>
</details>

Minor touch ups, should check on vertical padding

---

server/app/services/account.service.js
server/app/services/sendgrid-service.js
server/package-lock.json
server/package.json

Fixes #1738 
- Migrated date code from Moment.js to JavaScript Date methods
- Moment.js is deprecated
No visual changes as they remain the same.

1738 - Migrated date code from Moment.js to JavaScript Dates

---

server/__tests__/feedback.test.js
server/app/controllers/feedback.controller.js
server/app/schemas/feedback.post.js

Fixes #1624
- Implement server-side request validation for /api/feedbacks web api endpoint
Per issue #1624 
(none)
n/a

Implement /api/feedbacks web api test and validation

---

client/src/components/PdfPrint/PdfFooter.js
client/src/components/PdfPrint/PdfPrint.js
client/src/components/ProjectWizard/TdmCalculationContainer.js
client/src/components/ProjectWizard/TdmCalculationWizard.js
client/src/components/ProjectWizard/WizardFooter.js
client/src/components/Projects/ProjectTableRow.js
server/db/migration/V20240529.1948__add_dateSubmitted_column_1704.sql
server/db/migration/V20240626.1243__add_datesubmitted_col_to_project_select_sprocs_1759.sql

- Fixes #1759
- On PDF Printout, moved Results to above Project Details.
- Added status and Snapshot Submitted and Snapshot created lines to footer.
- Fixed format of Date Last Printed date.
- The submit feature is not yet implemented, so I manually put in a Submit date for the project "Curious Apartments" belonging to curious@dispostable.com to test.  You can view this by logging in as an admin user and looking for the project by name.
- Requested in Stakeholder meeting 6/25/24
(none)
<details>
[CuriousApartmentsBeforeIssue1759.pdf](https://github.com/user-attachments/files/16018553/CuriousApartmentsBeforeIssue1759.pdf)
</details>
<details> …

Changes to PDF Print format

---

client/src/components/ProjectWizard/WizardPages/ProjectSummary/ProjectSummary.js

Fixes #1763 
- Moved Project Details Section above the Strategies Selected section
- Per Bonnie's request

Re-arrange sections of the Summary Page

---

client/src/components/PdfPrint/PdfFooter.js
client/src/components/ProjectWizard/WizardFooter.js
client/src/components/ProjectWizard/WizardPages/ProjectSummary/ProjectSummary.js

Fixes #1772
- Modified Wizard Footer to make sure user is logged in before attempting to get their loginId
- To keep app from crashing.

1772 fix wizard footer bug

---

client/src/components/PdfPrint/PdfFooter.js
client/src/components/PdfPrint/PdfPrint.js
client/src/components/ProjectWizard/TdmCalculationContainer.js
client/src/components/ProjectWizard/WizardFooter.js

- Fixes #1773
- Under some circumstances footers on Summary page and PDF were showing "Invalid Date" for Snapshot Created and/or Snapshot Submitted dates.

Bug: was showing 'Invalid Date' for some dates

---

client/src/components/Feedback/ProjectList.js
client/src/components/PdfPrint/PdfFooter.js
client/src/components/PdfPrint/PdfPrint.js
client/src/components/ProjectWizard/TdmCalculationContainer.js
client/src/components/ProjectWizard/TdmCalculationWizard.js
client/src/components/ProjectWizard/WizardFooter.js
client/src/components/Projects/MultiProjectToolbarMenu.js
client/src/components/Projects/ProjectTableRow.js
client/src/components/Projects/ProjectsPage.js
client/src/helpers/util.js

Fixes #1775
- Move date and datetime formatting to utility functions
- Use these functions instead of coding formatting functions in the different components that need it.
- Components for the Wizard and PdpPrint were passing too many props (inconsistently - leading to bugs). Refactored to pass a project object prop instead.
- Maintaining these components was painful
(none)

Make date formatting consistent

---

client/src/helpers/util.js

Fixes #1775
- Format string for datetimes was incorrect
- To fix it.

Hotfix to datetime format

---

client/package-lock.json
package-lock.json
server/package-lock.json

Try to sync packagelock files

---

client/src/components/ProjectWizard/AffordableEdgeCaseModal.js
client/src/components/UI/AriaModal/ModalDialog.js

Fixes #1354
- Fixed layout problem introduced in previous attempt
-
-

Fix bug in ModalDialog

---

client/src/components/Projects/ProjectsPage.js

- Fixes #1801
- Bug fix to sorting  by Created By column

Fix bug in sorting by Created By column

---

client/src/components/Faq/ExpandButtons.jsx
client/src/components/Faq/FaqButtonContainer.jsx

Minor adjustments to Expand/Collapse All buttons

---

client/src/components/ProjectWizard/WizardPages/ProjectMeasures.js

- Fixes #1729
- See Issue #1729
-
-
- See Issue #1729
-
-

Fix typo in Strategies Page subtitle

---

client/src/components/Projects/ColumnHeaderPopups/DatePopup.js
client/src/components/UI/DateRangePicker.jsx

Fixes #1648
- Hack to make calendar popup appear inside the filtering popup
- to look better most of the time.
<details>
</details>
<details>
</details>

Hack to make date popups appear to be inside popup

---

client/package-lock.json
client/src/components/ProjectWizard/WizardPages/ProjectSummary/PointsEarnedMessage.jsx
package-lock.json

Fixes #1827 
- Made use of themes to ensure uniformity.
- Removed the line break to align the text to a single line.
- Removed the drop shadow from the text.
- Changed the font to "Subheading" style in the style guide.
- Changed warning icon color to "Warning (#E87D00)".
- Style changes from designers to make the overall UI better.
<details>
</details>
<details>
</details>

1827 cosmetic changes target points not reached infobox

---

client/package-lock.json
client/src/components/ProjectWizard/WizardSidebar/SidebarCart.js
package-lock.json

Fixes #1824 
- Updated typography font in infoboxes to "Paragraph" style
<details>
</details>
<details>
</details>

1824 typography changes target point infobox

---

client/src/components/ProjectWizard/WizardPages/ProjectSummary/PointsEarnedMessage.jsx

Fixes #1826 
-Removed the drop shadow from the text.
-Used the common theme to change the font to subHeading style.
- UI changes by the developer to make it visually pleasing.
<details>
</details>
<details>
</details>

Cosmetic changes to target points successful infobox - 1826

---

client/package-lock.json
client/package.json
client/src/components/Projects/ColumnHeaderPopups/ProjectTableColumnHeader.jsx
client/src/components/Projects/ColumnHeaderPopups/TextPopup.jsx
client/src/components/UI/DateRangePicker.jsx

Fixes #1911
- Changed popup NPM library to react-tiny-popover
-
-
- It automatically keeps the popup contents within the screen boundaries
- It better handles scrolling of the parent window, keeping the popup near its triggering component (i.e. the Column Header)
<details>
https://github.com/user-attachments/assets/10246666-fe0d-4c5d-aab5-251902ad699c
</details>
<details>
https://github.com/user-attachments/assets/d9637c9b-20a8-455c-9166-420f0c311d04
</details>

Changed to react-tiny-popover library for col sorting

---

client/src/components/Authorization/Login.jsx
client/src/components/Faq/DeleteFaqModal.jsx
client/src/components/Faq/SaveConfirmationModal.jsx
client/src/components/ProjectWizard/AffordableEdgeCaseModal.jsx
client/src/components/ProjectWizard/NavConfirmDialog.jsx
client/src/components/Projects/ColumnHeaderPopups/DatePopup.jsx
client/src/components/Projects/ColumnHeaderPopups/StatusPopup.jsx
client/src/components/Projects/ColumnHeaderPopups/TextPopup.jsx
client/src/components/Projects/ColumnHeaderPopups/VisibilityPopup.jsx
client/src/components/Projects/CopyProjectModal.jsx
client/src/components/Projects/CsvModal.jsx
client/src/components/Projects/DeleteProjectModal.jsx
client/src/components/Projects/DownloadProjectModal.jsx

- Fixes #1920
- See issue
- See issue
- See issue

Change Cancel/Close buttons to secondary (outlined) style

---

client/src/components/Projects/ProjectContextMenu.jsx
client/src/components/Projects/ProjectTableRow.jsx
client/src/components/Projects/ProjectsPage.jsx
client/src/components/Projects/ShareSnapshotModal.jsx
client/src/services/projectShare.service.js
server/app/controllers/projectShare.controller.js
server/app/routes/index.js
server/app/routes/projectShare.routes.js
server/app/schemas/projectShare.js
server/app/services/projectShare.service.js
server/db/migration/V20241008.1756__add_projectShare_table.sql
server/db/migration/V20241008.1757__add_projectShare_insert.sql
server/db/migration/V20241008.1758__add_projectShare_delete.sql
server/db/migration/V20241008.1759__add_projectShare_select_by_projectId.sql
server/db/migration/V20241008.1760__add_projectShare_select_by_Id.sql
server/db/migration/V20241008.1761__add_projectShare_test.sql

- Fixes #1700
- Added a project share table + SPROCs + API endpoints
- Created share snapshot modal and item in kebab menu
- Need to allow users to share snapshots with other users
<details>
</details>

Add ProjectShare table and share modal #1700

---

client/src/components/Layout/NavBar.jsx
client/src/components/Projects/ProjectContextMenu.jsx

Fixes #1949
- See Issue
-
-
- See Issue

Re-enable temporarily disabled features

---

client/src/components/Layout/NavBar.jsx
client/src/components/Projects/ProjectContextMenu.jsx
client/src/components/Projects/ProjectsPage.jsx

Fixes #1949 
-
-
-
-
-
-
<details>
</details>
<details>
</details>

1949  re enable partial features

---

client/src/App.js
client/src/components/ProjectWizard/TdmCalculationContainer.jsx
client/src/components/ProjectWizard/TdmCalculationWizard.jsx
client/src/components/ProjectWizard/WizardFooter.jsx
client/src/services/project.service.js
server/app/controllers/project.controller.js
server/app/routes/project.routes.js
server/app/services/project.service.js
server/db/migration/V20241112.1450__add_project_select_by_id_with_shared_email.sql

Fixes #1703
- Implement shared snapshot view link
- Adding sql migration and api endpoint
- to allow people to see snapshots shared with them
<details>
</details>

Implement shared snapshot view link #1703

---

client/src/components/Button/TertiaryButton.jsx
client/src/components/Projects/ProjectsPage.jsx

- Fixes #2000
- Fixes #2016 
- Fixes #2017
- When filters are modified, go to page 1 of results Issue #2000 
- Reset Filters Button - remove print icon Issue #2016 
- Reset Filters - clear search text as well as other criteria Issue #2017
As requested by PMs / UX / Design
<details>
</details>
<details>
</details>

Reset Filters changes, Go to page 1 when filters change

---

client/src/components/Projects/ColumnHeaderPopups/TextPopup.jsx

- Fixes #2015
- See Issue
-
- See Issue
n/a
See Issue

Fix Created By filter popup filtered list

---

client/src/components/Projects/ProjectContextMenu.jsx
client/src/components/Projects/ProjectTableRow.jsx
client/src/components/Projects/ProjectsPage.jsx

Fixes  
- #1657 
- Added Submit to LADOT button in the kebab menu of My Projects page.
- Users should be able to submit their form from the My Projects page for review.
tdm@hackforla.org account was used.
<details>
</details>
<details>
</details>

created submit to LADOT button in the kabob menu of my projects page

---

server/db/migration/V20250213.1035__rename_metro_dro_to_central_2095.sql

Fixes #2095
- Changed name of Metro DRO to Central
- Requested by City Planning
<details>
</details>
<details>
</details>

Change name of Metro DRO to Central

---

server/db/migration/V20250213.1134__set_maxValue_on_park_spaces_2052.sql

- Fixes #2052
- See Issue 
- See Issue
See 2/13/2025 comment on Issue

Limit PARK_SPACES to 9999999

---

client/src/components/Faq/FaqConfirmDialog.jsx
client/src/components/Layout/NavBarLogin.jsx
client/src/components/ProjectWizard/NavConfirmDialog.jsx
client/src/components/Projects/ProjectContextMenu.jsx
client/src/components/SubmitSnapshot/SubmitSnapshotPage.jsx
client/src/styles/theme.js

-Fixes #2044, #2045, #2048, #2050, #2012, #2064, #2020
- See Issues
-
-
- See issues
See Issues and Slides

Issues 2044, 2045, 2048, 2050, 2012, 2064, 2020

---

client/src/components/Authorization/SendEmailForm.jsx
client/src/components/Faq/FaqConfirmDialog.jsx
client/src/components/Feedback/FeedbackPage.jsx
client/src/components/Layout/NavBarLogin.jsx
client/src/components/ProjectWizard/NavConfirmDialog.jsx
client/src/components/ProjectWizard/WizardPages/Level0Page.jsx
client/src/components/Projects/ProjectContextMenu.jsx
client/src/components/SubmitSnapshot/SubmitSnapshotPage.jsx
client/src/styles/theme.js

- Fixes #2059
- Cosmetic design changes to the Wizard's Level 0 Page 
- See Issue
- See Issue
<details>
</details>
<details>
</details>

2059 legibility of level0 page

---

client/src/components/Layout/NavBarLogin.jsx
client/src/components/ProjectWizard/WizardPages/Level0Page.jsx

- Fixes #2059 - minor tweak
- Remove border from Level 0 Page infobox
- Per verbal request by Bonnie on 2/18/25
<details>
</details>
<details>
</details>

Remove border from level0page infobox

---

client/src/components/Modals/ActionProjectCopy.jsx
client/src/components/Modals/ActionProjectSnapshot.jsx
client/src/components/Modals/ActionSnapshotRename.jsx

- Fixes #1985 
- Adjustments to PR #2137
- See Issue
- See Issue
- See PR#2137

Minor adjustments to PR#2137

---

client/src/components/Checklist/ChecklistContent.jsx
client/src/components/Checklist/ChecklistModal.jsx
client/src/components/Modals/ActionSnapshotRename.jsx
client/src/components/Modals/ActionSnapshotShare.jsx
client/src/components/Modals/InfoWizardInapplicableStrategies.jsx
client/src/components/TermsAndConditions/TermsAndConditionsContent.jsx
client/src/components/TermsAndConditions/TermsAndConditionsModal.jsx

- Fixes #1986
- See #1986
- See #1986
<details>
- See #1986
</details>
<details>
- See #1986
</details>

Re-style Info and Other Modals

---

client/src/components/Modals/ActionProjectSnapshot.jsx
client/src/components/Modals/ActionProjectsCsv.jsx
client/src/components/Modals/WarningWizardAffordableEdgeCase.jsx

- Fixes #1986
- See Issue
- Comply with Design System
-
-
See Issue

Tweaks to modal dialogs

---

client/src/components/Projects/MultiProjectToolbarMenu.jsx
client/src/components/Projects/ProjectsPage.jsx

- Fixes #2140
- See Issue
- See Issue
<details>
</details>
<details>
</details>

Increase icons sizes on My Projects Page

---

client/src/components/Projects/MultiProjectToolbarMenu.jsx

- Fixes  #2180 
- made icons on my project page a pointer on hover (if not disabled)
- they should be pointers
can not record screen, it messes with the default cursor. You'll have to pull the changes to test.

fix: make project icon cursor a pointer if not default

---

client/src/components/Projects/ProjectTableRow.jsx
client/src/components/Projects/ProjectsPage.jsx

- Fixes #2096
-
-
-
-
-
-
<details>
</details>
<details>
</details>

Adjust Column Widths on My Project Page

---

client/src/components/Button/CopyAndEditProject.jsx
client/src/components/Modals/ActionCopyAndEditSnapshot.jsx
client/src/components/ProjectWizard/TdmCalculationContainer.jsx
client/src/components/ProjectWizard/TdmCalculationWizard.jsx
client/src/components/ProjectWizard/WizardFooter.jsx
client/src/components/UI/AriaModal/ModalDialog.jsx

Fixes #1795 
- Add feature to create and edit snapshot (turns copy into draft)
- A bit of refactoring
- Feature in ticket 1795
- cleaning up code
<details>
Video:
https://github.com/user-attachments/assets/c2838471-7aba-4868-a3de-c18e37395342
</details>

add feature to create a draft of project based on snapshot

---

client/src/components/Authorization/Login.jsx
client/src/components/Authorization/SendEmailForm.jsx
client/src/components/Faq/FaqButtonContainer.jsx
client/src/components/Layout/NavBarLogin.jsx
client/src/components/Modals/WarnngFaqLeave.jsx
client/src/components/ProjectWizard/Common/RuleLabel.jsx
client/src/components/ProjectWizard/RuleCalculation/RuleCalculation.jsx
client/src/components/ProjectWizard/RuleInput/ParkingProvidedRuleInput.jsx
client/src/components/ProjectWizard/RuleInput/RuleInput.jsx
client/src/components/ProjectWizard/RuleStrategy/RuleStrategy.jsx
client/src/components/ProjectWizard/WizardPages/Level0Page.jsx
client/src/components/ProjectWizard/WizardPages/ProjectDescriptions.jsx
client/src/components/Projects/ProjectContextMenu.jsx
client/src/components/ToolTip/ToolTipLabel.jsx
client/src/styles/theme.js

- Fixes #2050
- Fixes #2153 
- Fixes #2151
- See Issues
- See Issues
<details>
</details>
<details>
<summary>Visuals after changes are applied</summary> 
- Issue #2150
- Issue #2153 
- Issue #2151 
- 
</details>

Fix color of various UI Critical Color Elements

---

client/src/components/Layout/NavBar.jsx

- Fixes #2150 
- Removed the "Submit Snapshot" link for those that are not logged in
<details>
</details>
<details>
</details>

2150 remove submit snapshot link for not logged in

---

client/src/components/ArchiveDelete/ProjectsArchive.jsx
client/src/components/Authorization/Login.jsx
client/src/components/Modals/ActionProjectsCsv.jsx
client/src/components/Modals/csvData.jsx
client/src/components/ProjectWizard/WizardPages/ProjectDescriptions.jsx
client/src/components/SubmitSnapshot/SubmitSnapshotPage.jsx
server/app/services/sendgrid-service.js

- Fixes #2124
- see Issue
- See Issue
<details>
</details>
<details>
Archived Projects Page
CSV Download File
Submit Snapshot Page
My Projects Page
</details>

Change 'Saved' to 'Modified'

---

client/src/components/Feedback/FeedbackPage.jsx
client/src/components/Feedback/ProjectList.jsx

- Fixes #2256 
- Fixes #2171 
- Fixes #2172 
- Adjust column widths on Feedback page to use more of the page width, allocate sufficient width so date fields don't wrap, and the entire page scrolls horizontally if the page is too narrow.
- Fix logic for showing client-side validation of name on Feedback Page
- Re-located client-side validation message to below the corresponding input control
- Changed color of client-side validation error message to colorCritical
- 
- See Issues
<details>
</details>
<details>
</details>

Changes to Feedback Page

---

Dockerfile
client/vite.config.js

- Fixes #1706 
- Needed to update Dockerfile
- Deployment was failing

Attempt to fix Dockerfile for deployment

---

client/.eslintignore

- Fixes #2186
- Fixed eslint for the client project
- running eslint on the client folder would hang
<details>
```
$ npm run lint
> tdm-calculator-client@0.2.55 lint
> eslint -c .eslintrc.json --ignore-path .eslintignore  "**/*.{js,jsx}"
```
(note that process did not finish)
</details>
<details>
```
$ npm run lint
> tdm-calculator-client@0.2.55 lint
> eslint -c .eslintrc.json --ignore-path .eslintignore  "**/*.{js,jsx}"      
johnc@John-ThinkPad MINGW64 /c/git/hackforla/tdm-calculator/client (develop) 
$
```
(note that process finished and returned to the $prompt)
</details>

Fix client eslint

---

.github/ISSUE_TEMPLATE/Design Issue

**Note**: I'm not familiar with how the pull request workflow goes in TDM, especially with issue templates, so please excuse any lack of reviewers, assignees, or labels that are expected. I intended to have Marlena review this first, followed by John and Bonnie.
- Fixes #2305 
- I created a new template specifically for design issues.
- The current Blank Issue template does not contain most of the steps listed in the new [Issue Workflow](https://github.com/hackforla/tdm-calculator/wiki/Issue-Workflow).

Create "Design Issue" Template

---

client/src/components/Authorization/SendEmailForm.jsx
client/src/components/Authorization/UpdateAccount.jsx
client/src/components/ProjectWizard/RuleInput/ParkingProvidedRuleInput.jsx

- Fixes #2166 
- Fixes #2167
- Fixes #2168
- Fixes #2169 
- Fix alignment and/or color of a few client-side validation msgs.
- See Issues
<details>
(See Issues)
</details>
<details>
- #2166 and #2167
- #2168
- #2169
</details>

Alignment, color of validation msgs

---

.github/scripts/find-label-in-gh-issue.cjs
.github/workflows/slack-webhook-ping-design.yaml

- Fixes #2316 
- THIS IS A TEST TO MAKE SURE THE SLACK BOT IS WORKING AS INTENDED
-
<details>
</details>
<details>
</details>

feat: add design review slack ping workflow

---

package.json

- Fixes #2288
- changed API connectivity check route from `/api/rules` to `/api/calculations`
- this fixes a bug where you cannot run `npm start` from the root directory of the project
- n/a

Update backend server api connection endpoint

---

client/src/components/Projects/ColumnHeaderPopups/MultiSelectText.jsx
client/src/components/Projects/ColumnHeaderPopups/TextPopup.jsx
client/src/components/UI/RadioButton.jsx
client/src/components/UI/UniversalSelect.jsx
client/src/styles/App.scss

- Fixes #2111 
This PR changes the border and background colors of the radio button, checkbox, and dropdown input controls.
- styled `RadioButton` component using react-jss
- styled `UniversalSelect` (aka dropdown) component
- styled checkbox input using scss
- Before, the radio button and checkbox components were using the browser default colors and styles, which means that it would look different on different browsers and operating systems
- This PR sets color styles for default, selected, and hover states so that they are standardized across browsers, including chrome, safari and mobile
- They are set according to these designs:
- https://github.com/hackforla/tdm-calculator/issues/1839#issuecomment-2638891783
- https://www.figma.com/design/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=1 …

2111 style input controls

---

client/src/components/Feedback/ProjectList.jsx

- Fixes #2318
- Quick fix to PR#2377 to center table caption above centered table.
-

Feedback Page - center table heading

---

client/src/App.jsx
client/src/components/Layout/NavBar.jsx
client/src/components/Submissions/SubmissionsAdminPage.jsx
client/src/components/Submissions/SubmissionsPage.jsx
client/src/services/project.service.js
server/app/controllers/project.controller.js
server/app/routes/project.routes.js
server/app/services/project.service.js
server/db/migration/V20250417.1734__project_submission_changes_2367.sql

- Fixes #2369
- Altered and added tables to db to support Submissions and Manage Submissions Pages
- Added required stored procedures and endpoints
- Stubbed out Submission and Submission Admin Pages with Menu placeholders
- See Issue
Login as tdm-dev+user@hackforla.org on dev environment for Submissions Page
Login as tdm-dev+admin@hackforla.org on dev environment for Submission Admin Page
<details>
(none)
</details>
<details>
</details>

Implement back-end for Submissions and Submission Admin Pages

---

client/src/App.jsx
client/src/components/Layout/NavBar.jsx
client/src/components/ManageSubmissions/ManageSubmissionsPage.jsx
client/src/components/ProjectWizard/RuleInput/RuleInput.jsx

- Fixes #2421
- Changed "Submission Admin" to "Manage Submissions" in UI
- See Issue
n/a
<details>
</details>
<details>
</details>

2421 change name to manage submissions

---

client/src/components/ManageSubmissions/ManageSubmissionsPage.jsx
client/src/components/ManageSubmissions/SubmissionTableRow.jsx
client/src/components/Projects/ColumnHeaderPopups/ProjectTableColumnHeader.jsx
client/src/components/Projects/ColumnHeaderPopups/TextPopup.jsx
client/src/helpers/Constants.js
server/db/migration/V20250423.1624__sproc_changes _2454.sql

- Partial Implementation of #2454
- Created read-only version of the gird with most of the filtering and sorting working
-
Any admin account.
<details>
</details>
<details>
</details>

Manage Submissions - take 1

---

client/src/components/Faq/CategoryInputContainer.jsx
client/src/components/Faq/FaqButtonContainer.jsx
client/src/components/ManageSubmissions/ManageSubmissionsPage.jsx
client/src/components/ManageSubmissions/SubmissionTableRow.jsx
client/src/components/Projects/ColumnHeaderPopups/BooleanPopup.jsx
client/src/components/Projects/ColumnHeaderPopups/NumberPopup.jsx
client/src/components/Projects/ColumnHeaderPopups/ProjectTableColumnHeader.jsx
client/src/components/Projects/ColumnHeaderPopups/StringPopup.jsx
server/db/flyway-config.js

- Part 2 of Incremental Implementation of  #2454
- Re-ordered columns per design Issue #1953 (in progress)
- Implemented filtering & sorting for boolean (onHold), and enum data type cols (invoice Status, dro, approval Status)
- Added ID column left-padded with 0s
- Reduced vertical space
- Extrapolating from current description of Issue #1953
<details>
</details>
<details>
</details>

Refine filters, re-order columns

---

.husky/pre-commit
client/src/components/Projects/MultiProjectToolbarMenu.jsx
package.json

- Fixes #2487
- Update husky configuration to comply with Husky v9
- to prevent a deprecation warning
n/a
n/a

Fix pre-commit hook warning

---

client/src/components/Feedback/ProjectList.jsx

- Bug fix to PR #2483
- Center the table heading on the Feedback page

Fix to PR#2483

---

client/src/App.jsx
client/src/components/Layout/NavBar.jsx
client/src/components/Submissions/SubmissionsPage.jsx

- Fixes #2372
- Implemented Submissions Page
- To have a Submissions page
Any non-admin user   - use tdm-dev+user@hackforla.org in dev environment for now, since it's the only account with non-trivial data.
<details>
</details>
<details>
</details>

Implement Submissions Page

---

server/app/services/project.service.js
server/db/migration/V20250502.1115__relax-security-on-project-updatedroid-sproc_2409.sql

- Back-end changes for  #2347
- Modified PRoject_UpdateDroId to allow a user to update the dro on projects for which they are the author.
- To set the stage for front-end changes that allow the user to edit the dro of their projects.
Non-admins
n/a

Back end changes to allow author to edit droId

---

client/src/components/Modals/ActionManageSubmission.jsx
client/src/components/Modals/ActionManageSubmission1.jsx
client/src/components/Submissions/ManageSubmissionsPage.jsx
client/src/components/Submissions/SubmissionTableRow.jsx
client/src/components/Submissions/SubmissionsPage.jsx
client/src/helpers/Constants.js
client/src/helpers/util.js
client/src/services/project.service.js

- Added Status Editing to #2454
- Added Modal dialog for editing the status of submissions to the Manage Submissions Page
- Per issue
any admin
<details>
</details>
<details>
</details>

2454 part5

---

client/src/components/Feedback/FeedbackPage.jsx

- Fixes #2498 
- Aligned button to right of form
- For Devs: added wrapper to the button that uses the same class as the form container. I did this so that when there are projects rendered they don't get shifted to the right.
<details>
</details>
<details>
</details>

fix: align button to right of form

---

server/db/migration/V20250521.1637__about-table-sprocs_1531.sql

- Database migration to support  #1531
- Created DB migration script to implement stored procedure and one user-defined data type for the About table editing.
- Pre-requisite to front-end work on the issue
n/a
<details>
n/a
</details>
<details>
n/a
</details>

DB Migration for About sprocs

---

server/db/migration/V20250602.1535__fix_spelling_error_2492.sql

- Fixes #2492 
create migration file for replace misspelled words in CalculationRule table
To fix spelling error in db 
N/A
before:
after:

Fix database spelling error

---

client/src/components/Layout/NavBar.jsx
client/src/components/Layout/NavBarLogin.jsx
client/src/components/Projects/ColumnHeaderPopups/ProjectTableColumnHeader.jsx

- Fixes #2465
- Adding styles to nav bar on login and logged out for hover and active locations
- Updating filter header icons on hover and active in my projects page
- Better visibility in active links and active filters on both navigation page and projects page (on login) 
- I used basic user credentials found on 1password
<details>
[navigation hover state showcase before](https://github.com/user-attachments/assets/da3c746b-b7a3-451c-ab7a-2201f3737104)
</details>
<details>
[navigation hover state …

2465 navigation hover state

---

client/src/components/ArchiveDelete/RolesArchive.jsx
client/src/components/ArchiveDelete/RolesDeleteContextMenu.jsx
client/src/components/ArchiveDelete/RolesUnarchiveContextMenu.jsx
client/src/styles/theme.js

- Fixes #2502 
- Updated the table for archived accounts.
- Added search functionality.
- The archived accounts page was updated to implement the redesign for visual consistency.
tdm-dev+security@hackforla.org account was used.
<details>
</details>
<details>
</details>

updated archived accounts page

---

client/src/components/Layout/Header.jsx
client/src/components/Layout/NavBar.jsx
client/src/components/Layout/NavBarLogin.jsx

- Fixes #2411 
- added aria label to hamburger menu as well as other aria attributes
- accessibility
<details>
N/A
</details>
<details>
This can't really be shown with an image, here's a video with a screen reader's captions beside it
https://github.com/user-attachments/assets/2dc75629-d038-4246-98ec-555169434649
</details>
In order to test these changes, you need to run a screen reader (cmd+f5 on mac, unsure on windows/linux)

2411 accessibility mobile header

---

server/db/migration/V20250813.2045__modify-mobility-investment-strategies_2576.sql

- Fixes #2576
- See Issue
- ALSO Note that I created a series of videos that explains exactly how these changes were implemented [here](https://drive.google.com/drive/folders/1KQwaOnxJfVQ_-SCYm9C3JCL_tlT3pVjv?usp=drive_link).
- Requested by Alexander Wikstrom of LADOT
<details>
</details>
<details>
</details>

2576 modify mobility investment strategies

---

server/db/migration/V20250820.1934__update_calculation_rule_names_parkcondo_sftradeschool.sql

- Fixes PR #2628
- Fixed incorrect SQL Update statement
- So it would work
n/a
n/a

Fix to PR #2628

---

server/db/migration/V20250917.1558__update_calculation_rule_mobility_investment_1_description.sql

- Fixes #2614 
- Updated the copy on mobility investment 1's tooltip description
- match new copy shown in ticket 2614
<details>
</details>
<details>
</details>
Once this has been reviewed and approved, we have to run a migration on the shared db to see the changes in the staging/prod websites.

fix: update mobility investment tooltip description
